const translations = {
    en: {
        nav_capabilities: "Capabilities",
        nav_innovation: "Innovation",
        nav_about: "About Us",
        nav_contact: "Contact",
        hero_title: 'Defense Technologies <br>of the <span class="logo-accent">Future</span>',
        hero_subtitle: "Shaping global security through next-generation high-precision production solutions.",
        btn_explore: "Explore",
        btn_contact: "Contact",
        about_title: "About Us",
        about_p1: "Megatech Defense is an innovative engineering firm offering high-precision production solutions in CNC sliding head machine technologies.",
        about_p2: "We specialize in manufacturing precision parts for mission-critical sectors, including defense, automotive, aerospace, medical, and industrial production.",
        about_p3: "Leveraging our state-of-the-art CNC sliding head machinery and robust infrastructure, we produce components with complex geometries to the highest quality standards. Our serial production processes are engineered for reliability, ensuring dimensional precision and customer satisfaction at every stage.",
        about_p4: "Our mission is to integrate advanced technology with superior engineering and precision manufacturing, delivering the reliable solutions our industry demands while maintaining a commitment to sustainable quality.",
        exp_text: "Years of Experience",
        innovation_title: "Innovation",
        inn_card1_title: "AI-Powered Precision",
        inn_card1_desc: "Integrating advanced artificial intelligence to optimize CNC processes and ensure zero-defect manufacturing.",
        inn_card2_title: "Autonomous Systems",
        inn_card2_desc: "Developing high-precision components for the next generation of land, air, and sea autonomous defense platforms.",
        inn_card3_title: "Tactical Materials",
        inn_card3_desc: "Expertise in working with advanced aerospace-grade alloys and composites for mission-critical applications.",
        contact_title: "Contact Us",
        contact_h3: "Get in Touch",
        contact_desc: "Our team of experts is ready to discuss your high-precision manufacturing requirements.",
        info_email: "Email:",
        info_location: "Location:",
        info_phone: "Phone:",
        placeholder_name: "Your Name",
        placeholder_email: "Your Email",
        placeholder_subject: "Subject",
        placeholder_message: "Your Message",
        btn_send: "Send Message",
        footer_desc: "Leading the way in advanced defense technologies, aerospace engineering, and tactical systems. Engineering the future of global security.",
        footer_capabilities: "CAPABILITIES",
        footer_resources: "RESOURCES",
        footer_contact: "CONTACT",
        link_aerospace: "Aerospace Systems",
        link_naval: "Naval Engineering",
        link_land: "Land Defense",
        link_cyber: "Cyber Security",
        link_docs: "Technical Docs",
        link_career: "Career Portal",
        link_press: "Press Room",
        link_sustainability: "Sustainability",
        footer_location: "Saray Mahallesi, 30. Cd. 15B 06980 Kahramankazan Ankara, Türkiye",
        footer_rights: "All rights reserved.",
        link_privacy: "Privacy Policy",
        link_terms: "Terms of Service",
        contact_page_title: 'Contact Our <span class="logo-accent">Experts</span>',
        contact_page_subtitle: "We are ready to provide the precision engineering solutions your project requires.",
        contact_desc_dedicated: "Reach out to our engineering team directly for technical inquiries or quote requests.",
        info_office: "Corporate Office:",
        office_location: "Saray Mahallesi, 30. Cd. 15B<br>06980 Kahramankazan Ankara<br>Türkiye",
        label_name: "Full Name",
        label_email: "Email Address",
        label_sector: "Industry Sector",
        label_message: "Your Message",
        placeholder_name_val: "John Doe",
        placeholder_email_val: "john@example.com",
        placeholder_message_val: "Describe your project requirements...",
        btn_send_secure: "Contact Our Team",
        nav_blog: "BLOG",
        blog_title: "Defense Industry & Technology Blog",
        blog_subtitle: "Insights into the future of precision manufacturing and defense tech.",
        read_more: "Read More",
        blog_post1_title: "Role of CNC Sliding Head Technology in Defense",
        blog_post1_excerpt: "Critical importance of CNC sliding head machines in micro-precision parts for modern defense platforms.",
        blog_post2_title: "Localization in Turkish Defense & Megatech",
        blog_post2_excerpt: "Our local production solutions and engineering vision reducing foreign dependency in national projects.",
        blog_post3_title: "AI-Powered Precision Manufacturing",
        blog_post3_excerpt: "Next-generation control systems eliminating error rates with AI integration in our production lines.",
        blog_post4_title: "High-Precision in Aerospace",
        blog_post4_excerpt: "Quality control and tolerance management in aerospace-grade part manufacturing.",
        blog_post5_title: "Critical Components for Autonomous Systems",
        blog_post5_excerpt: "Manufacturing high-strength mechanical components for UAVs and land autonomous vehicles.",
        blog_post6_title: "Sustainable Quality in Defense",
        blog_post6_excerpt: "Material selection and heat treatment processes for reliable and long-lasting defense systems.",
        blog_post7_title: "National Combat Aircraft & Precision Engineering",
        blog_post7_excerpt: "Overview of high-tech part manufacturing processes for the KAAN project.",
        blog_post8_title: "UAV & UCAV Subsystem Manufacturing",
        blog_post8_excerpt: "Critical mechanical parts and technological details for Turkey's pride, the UAVs.",
        blog_post9_title: "Mechanical Precision in Armored Vehicles",
        blog_post9_excerpt: "Balancing durability and precision in heavy armored vehicle platforms.",
        blog_post10_title: "Material Engineering in Naval Systems",
        blog_post10_excerpt: "Corrosion-resistant high-tech part production for submarines and warships.",
        blog_post11_title: "Rocket & Missile Systems Manufacturing",
        blog_post11_excerpt: "Advanced machining methods for missile components requiring high speed and temperature resistance.",
        blog_post12_title: "Medical Device & Defense Technology Synergy",
        blog_post12_excerpt: "Transferring medical precision to defense: An engineering bridge between two sectors.",
        blog_post13_title: "Industry 4.0 & Defense Integration",
        blog_post13_excerpt: "Smart factories and digital transformation processes in the defense industry.",
        blog_post14_title: "Technical Excellence in Defense Exports",
        blog_post14_excerpt: "Competitive power and high quality standards of the Turkish defense industry in global markets.",
        blog_post15_title: "Megatech Vision 2030",
        blog_post15_excerpt: "Megatech's strategic goals and innovation roadmap in future defense technologies.",
        back_to_blog: "Back to Blog",
        blog_post4_p1: "The aerospace sector has redefined the concept of tolerance. A 0.05 mm thickness difference in an aircraft engine fan blade can lead to metal fatigue and disaster at 30,000 feet. In space systems, these tolerances drop to nanometer levels.",
        blog_post4_h2_1: "Precision Manufacturing in Aerospace",
        blog_post4_p2: "At our facilities certified with the AS9100D aerospace quality management system, we produce these critical components:",
        blog_post4_li1: "Turbine Housings: Manufacturing from superalloys (Inconel, Waspaloy) operating above 1000°C.",
        blog_post4_li2: "Hydraulic Actuator Parts: Precision shafts requiring zero leakage for aircraft landing gear and wing flaps.",
        blog_post4_li3: "Injection Systems: Micro nozzles that spray fuel into the combustion chamber in jet engines.",
        blog_post4_p3: "Every part is three-dimensionally controlled post-production with CMM (Coordinate Measuring Machine) and optical scanners, and subjected to the strictest criteria of aerospace standards. We follow this precision in the KAAN, HÜRJET, and GÖKBEY projects.",
        blog_post5_p1: "Autonomous systems like UAVs, UCAVs, and unmanned ground vehicles are changing the nature of warfare. However, the heart of these systems is not batteries or software; it's the mechanical power transmission organs that provide mobility.",
        blog_post5_h2_1: "Critical Components for Autonomous Platforms",
        blog_post5_p2: "Megatech develops these critical components for autonomous platforms:",
        blog_post5_li1: "Ball Bearing Systems: Ceramic ball bearings resistant to 100,000 rpm for high-speed drone motors.",
        blog_post5_li2: "Actuator Shafts: Wear-resistant carbide-coated shafts that pass the 10,000-hour life test in electro-mechanical actuators.",
        blog_post5_li3: "Reducer Gears: Planetary gear systems requiring high torque in ground autonomous vehicles.",
        blog_post5_p3: "Providing direct supply to Turkey's leading UAV manufacturers, Megatech guarantees the uninterrupted mission of national autonomous systems by eliminating foreign dependency on these components.",
        blog_post6_p1: "The life of a fighter jet is 30-40 years. During this time, its engine is overhauled many times, but the fuselage and critical structural parts do not change. This is where 'sustainable quality' comes in: A part performing just as well 30 years later as it did the day it was produced.",
        blog_post6_h2_1: "Megatech Quality Philosophy:",
        blog_post6_li1: "Material Selection: Use of aerospace-grade titanium (Ti-6Al-4V) as well as high-strength steels like 4340, 300M, 17-4 PH.",
        blog_post6_li2: "Heat Treatment Processes: Tempering, quenching, and cryogenic processes applied under atmospheric control in vacuum furnaces.",
        blog_post6_li3: "Surface Treatments: Maximizing corrosion resistance with nickel plating, cadmium plating, or passivation preferred in aerospace.",
        blog_post6_p2: "Every part coming out of Megatech is subjected to rigorous environmental tests (temperature cycle, salt fog, vibration). Quality is not a starting point, but an end point.",
        blog_post7_p1: "KAAN is a concrete indicator of the point Turkey has reached in the defense industry. This project is not just about building an aircraft; it is also a test of a country's precision engineering capability.",
        blog_post7_h2_1: "National Combat Aircraft and Precision Engineering",
        blog_post7_p2: "At Megatech, our role in the KAAN project includes the manufacturing of the aircraft's most critical mechanical sub-systems:",
        blog_post7_li1: "Cockpit Safety Lock Mechanisms: Low-weight and high-strength mechanisms that ensure the pilot stays safe while traveling at thousands of km/h.",
        blog_post7_li2: "Weapon Bay Actuators: Hydraulic systems that allow guided munitions hidden inside the fuselage to open and close within seconds.",
        blog_post7_li3: "Landing Gear Support Elements: Shock-absorbing parts that ensure the aircraft over 20 tons stops smoothly and safely at the moment of landing.",
        blog_post7_p3: "Each of these components is produced in 5-axis machines with hours of processing by removing chips from block material. The traceability of each part is digitally recorded from production to assembly.",
        blog_post8_p1: "Bayraktar TB2, AKINCI, and ANKA... These vehicles are not only Turkey's pride but also success stories that have entered global defense literature. Megatech produces thousands of critical sub-components that are the unsung heroes of these platforms.",
        blog_post8_h2_1: "UAV and UCAV Subsystem Manufacturing",
        blog_post8_p2: "Critical UAV components we produce:",
        blog_post8_li1: "Trim Actuator Bodies: The main body of the servo motors that control the aircraft's flight surfaces.",
        blog_post8_li2: "Fuel Pump Shaft: Specially designed wear-resistant shaft that operates smoothly even at high altitudes and low temperatures.",
        blog_post8_li3: "Parachute System Mechanism: Non-pyrotechnic mechanical triggers that enable the deployment of the parachute if the UAV fails.",
        blog_post8_p3: "The Megatech difference: All of these parts are produced with local capital and local engineering at high volumes and competitive prices, and are subjected to NATO standard tests before entering the inventory of the Turkish Armed Forces.",
        blog_post9_p1: "When it comes to armored vehicles, the first thing that comes to mind is durability. True; an Altay tank is over 60 tons and operates under direct fire. However, despite this weight, the mechanical systems that provide mobility to these vehicles require watchmaker precision.",
        blog_post9_h2_1: "Mechanical Precision in Armored Vehicles",
        blog_post9_p2: "Megatech's contribution to armored vehicle platforms:",
        blog_post9_li1: "Track Pins and Bushings: High-carbon steel pins that ensure the track system, carrying tons of load, performs for hundreds of hours without wearing out.",
        blog_post9_li2: "Turret Rotation Reducer Gears: Special gear geometries that can withstand the impulsive recoil of the gun while the tank turret rotates 360 degrees.",
        blog_post9_li3: "Shock Absorber Cylinders: Honed cylinder inner surfaces of hydraulic units that stabilize the body on rugged terrain.",
        blog_post9_p3: "All of these parts are meticulously processed by Megatech engineers, with the awareness that millimetric deviations can directly affect the combat capability of the vehicle.",
        blog_post10_p1: "Salt water is a mechanical engineer's worst enemy. Submarines and warships are challenging platforms that are constantly exposed to corrosion and operate under deep pressure. Megatech is pushing the boundaries of material engineering for naval systems.",
        blog_post10_h2_1: "Megatech Solutions Against Corrosion",
        blog_post10_p2: "Our specialized solutions for naval systems:",
        blog_post10_li1: "Shaft and Propeller Hubs: Production from duplex and super duplex stainless steels (e.g., 2205, 2507). These materials show superior resistance to chloride ions found in seawater.",
        blog_post10_li2: "Valves and Fasteners: Sealing elements manufactured from Monel (nickel-copper alloy) or Hastelloy.",
        blog_post10_li3: "Critical Bolts: Aerospace-grade titanium (Grade 5) or high-strength steels coated with nickel-cobalt.",
        blog_post10_p3: "Megatech supports the Turkish Naval Forces in performing long-lasting and reliable missions in blue waters with these special alloy parts provided for MİLGEM and MİLDEN projects.",
        blog_post11_p1: "From the moment a missile is launched, it exceeds the speed of sound within seconds and is exposed to temperatures of hundreds of degrees. In this environment, even the smallest material error leads to the missile exploding before reaching its target. Megatech is a reliable solution partner in these high-risk productions.",
        blog_post11_h2_1: "Rocket and Missile Systems Manufacturing",
        blog_post11_p2: "Our production range:",
        blog_post11_li1: "Rocket Engine Body: Precision tube manufacturing from 15-5 PH stainless steel, resistant to high temperature and pressure.",
        blog_post11_li2: "Nozzle Holders: Special ceramic or tungsten alloy parts against corrosive gases formed by fuel combustion.",
        blog_post11_li3: "Guidance Fin Shaft: Precision shaft that allows the small fins directing the missile to make 40-degree turns per second.",
        blog_post11_p3: "All of our missile components are developed entirely with Megatech engineering, without foreign technology licenses, and are used in projects carried out with leading institutions like ROKETSAN.",
        blog_post12_p1: "At first glance, the two sectors seem very far from each other. One saves lives, the other protects. However, when looking at the engineering infrastructure, there is a strong bridge between medical devices and defense technologies: Precision machining.",
        blog_post12_h2_1: "Synergy of Medical Device and Defense Technologies",
        blog_post12_p2: "Megatech uses the synergy between these two sectors in the most efficient way:",
        blog_post12_li1: "Medical Grade Bone Screw - Defense Counterpart: Missile body connection bolt",
        blog_post12_li2: "Surgical Instrument (Stainless 316L) - Defense Counterpart: Submarine valve bodies",
        blog_post12_li3: "Implant Prosthesis (Titanium) - Defense Counterpart: KAAN aircraft fuselage parts",
        blog_post12_p3: "The nanometer-level precision experience we gained in the medical sector provides us with a great advantage in the defense industry. Conversely, the robust quality control systems we developed in the defense industry form the basis of our medical device production.",
        blog_post13_p1: "The fourth industrial revolution is transforming production facilities. Now, not only factories producing parts, but 'smart factories' that produce data, analyze and optimize themselves create a competitive advantage. Megatech has implemented all components of Industry 4.0 specifically for the defense industry.",
        blog_post13_h2_1: "Megatech Smart Factory Components",
        blog_post13_p2: "Our Industry 4.0 approach:",
        blog_post13_li1: "Internet of Things (IoT): Every machine and every measuring device is connected to a central network. Production data is monitored instantly.",
        blog_post13_li2: "Digital Twin: Before a part is mounted on a machine, all process steps are tested in a simulation environment, and errors are eliminated in the virtual environment.",
        blog_post13_li3: "ERP and MES Integration: Every stage from raw material entry to shipment is tracked with barcodes and RFID. The customer can see instantly where their part is.",
        blog_post13_p3: "With this transformation, Megatech has risen to the position of not just a supplier but also a technology solution partner in the defense industry.",
        blog_post14_p1: "In the last 10 years, the Turkish defense industry has not only met its own needs but has become one of the world's largest exporters. The biggest power behind this success is high-tech production centers at the SME level like Megatech.",
        blog_post14_h2_1: "Technical Excellence in Defense Exports",
        blog_post14_p2: "How do we compete in the global market?",
        blog_post14_li1: "Certification Power: With our AS9100D and ISO 9001:2015 certificates, we are approved suppliers of giant defense firms in Europe and the Middle East.",
        blog_post14_li2: "Cost and Efficiency: With CNC sliding head technology, we offer competitive prices by producing 40% faster and with less waste compared to traditional methods.",
        blog_post14_li3: "On-Time Delivery: With our advanced production planning software, we leave no room for delay in critical projects.",
        blog_post14_p3: "As Megatech, we proudly carry the 'Made in Türkiye' stamp on every exported part and prove the quality of Turkish engineering to the world.",
        blog_post15_p1: "For Megatech, the future is more exciting than yesterday. At the center of our 2030 vision is making Turkey a world-leading base in precision manufacturing technologies.",
        blog_post15_h2_1: "Megatech Vision 2030",
        blog_post15_p2: "Our future goals:",
        blog_post15_li1: "Full Automation: Making 90% of our production lines operational without human intervention by 2030.",
        blog_post15_li2: "Next-Generation Alloys: Specializing in the processing of graphene-reinforced composites and ultra-light magnesium alloys.",
        blog_post15_li3: "Global Engineering Offices: Becoming a global brand by supporting our Ankara-based production with our engineering offices in Europe and America.",
        blog_post15_p3: "We are not just making parts; we are building the future of security. As the Megatech family, we thank all our stakeholders who are with us on this great journey."
    },
    tr: {
        nav_capabilities: "YETENEKLER",
        nav_innovation: "İNOVASYON",
        nav_about: "HAKKIMIZDA",
        nav_blog: "BLOG",
        nav_contact: "İLETİŞİM",
        hero_title: 'GELECEĞİN SAVUNMA <br><span class="logo-accent">TEKNOLOJİLERİ</span>',
        hero_subtitle: "Yüksek hassasiyetli üretim çözümleri ile global güvenliğe yön veriyoruz.",
        btn_explore: "KEŞFEDİN",
        btn_contact: "İLETİŞİM",
        about_title: "HAKKIMIZDA",
        about_p1: "Megatech Savunma, CNC kayar otomat işleme teknolojilerinde yüksek hassasiyetli üretim çözümleri sunan yenilikçi bir mühendislik firmasıdır.",
        about_p2: "Savunma sanayi başta olmak üzere otomotiv, havacılık, medikal ve endüstriyel üretim sektörlerine yönelik hassas parça imalatı gerçekleştirmektedir.",
        about_p3: "Modern CNC kayar otomat makineleri ve güçlü üretim altyapımız sayesinde; karmaşık geometrilere sahip parçaları yüksek kalite standartlarında, seri ve güvenilir şekilde üretmekteyiz. Üretim süreçlerimizin her aşamasında kalite kontrol, ölçü hassasiyeti ve müşteri memnuniyeti ön planda tutulmaktadır.",
        about_p4: "Megatech Savunma olarak hedefimiz; teknolojiyi, mühendisliği ve hassas üretimi bir araya getirerek sektörün ihtiyaç duyduğu güvenilir çözümleri sunmak ve üretimde sürdürülebilir kalite anlayışını devam ettirmektir.",
        exp_text: "Yıllık Tecrübe",
        innovation_title: "İNOVASYON",
        inn_card1_title: "YAPAY ZEKA DESTEKLİ HASSASİYET",
        inn_card1_desc: "CNC süreçlerini optimize etmek ve sıfır hata üretim sağlamak için gelişmiş yapay zekayı entegre ediyoruz.",
        inn_card2_title: "OTONOM SİSTEMLER",
        inn_card2_desc: "Yeni nesil kara, hava ve deniz otonom savunma platformları için yüksek hassasiyetli bileşenler geliştiriyoruz.",
        inn_card3_title: "TAKTİK MATERYALLER",
        inn_card3_desc: "Kritik görev uygulamaları için gelişmiş havacılık sınıfı alaşımlar ve kompozitler üzerinde uzmanlık.",
        contact_title: "İLETİŞİM",
        contact_h3: "İLETİŞİME GEÇİN",
        contact_desc: "Uzman ekibimiz, yüksek hassasiyetli üretim ihtiyaçlarınızı görüşmek için hazır.",
        info_email: "E-posta:",
        info_location: "Konum:",
        info_phone: "Telefon:",
        placeholder_name: "Adınız",
        placeholder_email: "E-posta Adresiniz",
        placeholder_subject: "Konu",
        placeholder_message: "Mesajınız",
        btn_send: "MESAJ GÖNDER",
        footer_desc: "Gelişmiş savunma teknolojileri, havacılık mühendisliği ve taktik sistemlerde öncü. Küresel güvenliğin geleceğini inşa ediyoruz.",
        footer_capabilities: "YETENEKLER",
        footer_resources: "KAYNAKLAR",
        footer_contact: "İLETİŞİM",
        link_aerospace: "Havacılık Sistemleri",
        link_naval: "Deniz Mühendisliği",
        link_land: "Kara Savunması",
        link_cyber: "Siber Güvenlik",
        link_docs: "Teknik Belgeler",
        link_career: "Kariyer Portalı",
        link_press: "Basın Odası",
        link_sustainability: "Sürdürülebilirlik",
        footer_location: "Saray Mahallesi, 30. Cd. 15B 06980 Kahramankazan Ankara, Türkiye",
        footer_rights: "Tüm hakları saklıdır.",
        link_privacy: "Gizlilik Politikası",
        link_terms: "Kullanım Şartları",
        contact_page_title: 'UZMANLARIMIZLA <span class="logo-accent">İLETİŞİME GEÇİN</span>',
        contact_page_subtitle: "Projenizin gerektirdiği hassas mühendislik çözümlerini sunmaya hazırız.",
        contact_desc_dedicated: "Teknik sorularınız veya fiyat teklifi talepleriniz için doğrudan mühendislik ekibimize ulaşın.",
        info_office: "Genel Merkez:",
        office_location: "Saray Mahallesi, 30. Cd. 15B<br>06980 Kahramankazan Ankara<br>Türkiye",
        label_name: "Ad Soyad",
        label_email: "E-posta Adresi",
        label_sector: "Sektör",
        label_message: "Mesajınız",
        placeholder_name_val: "Ahmet Yılmaz",
        placeholder_email_val: "ahmet@ornek.com",
        placeholder_message_val: "Proje gereksinimlerinizi açıklayın...",
        btn_send_secure: "EKİBİMİZLE İLETİŞİME GEÇİN",
        nav_blog: "BLOG",
        blog_title: "Savunma Sanayii ve Teknoloji Bloğu",
        blog_subtitle: "Hassas üretim ve savunma teknolojilerinin geleceğine dair güncel yazılar.",
        read_more: "Devamını Oku",
        blog_post1_title: "CNC Kayar Otomat Teknolojilerinin Savunma Sanayiindeki Rolü",
        blog_post1_excerpt: "Modern savunma platformlarında ihtiyaç duyulan mikro-hassasiyetteki parçaların üretiminde CNC kayar otomatların kritik önemi.",
        blog_post1_p1: "Savunma sanayiinde kullanılan her bir parça, hayati önem taşır. Bir füzenin güdüm sistemi, bir İHA'nın motor bloğu veya bir zırhlı aracın şanzıman dişlisi… Bu parçaların tamamı, mikro-metre seviyesinde hassasiyetle üretilmek zorundadır. İşte bu noktada CNC kayar otomat teknolojileri devreye girer.",
        blog_post1_h2_1: "Neden CNC Kayar Otomat?",
        blog_post1_p2: "Geleneksel torna tezgahlarından farklı olarak kayar otomatlar, malzemenin eksenel hareketiyle birlikte takımın sabit kaldığı bir prensiple çalışır. Bu yöntem, özellikle uzun ve ince çaplı iş parçalarında:",
        blog_post1_li1: "Eşsiz bir yuvarlaklık hassasiyeti (0.002 mm'ye kadar)",
        blog_post1_li2: "Yüksek yüzey kalitesi (Ra 0.2 μm)",
        blog_post1_li3: "Dakikada 12.000 devire kadar işleme kabiliyeti sunar.",
        blog_post1_p3: "Savunma platformlarında ihtiyaç duyulan enjektör nozulları, hassas mil bağlantı elemanları ve sensör gövdeleri tam da bu hassasiyet seviyesini gerektirir. Megatech olarak, Alman ve Japon menşeli en ileri kayar otomat teknolojileri ile Türk savunma sanayiinin kritik parça ihtiyacını %100 yerlilik oranıyla karşılıyoruz.",
        blog_post2_title: "Türk Savunma Sanayiinde Yerlileşme ve Megatech",
        blog_post2_excerpt: "Milli projelerde dışa bağımlılığı azaltan yerli üretim çözümlerimiz ve mühendislik vizyonumuz.",
        blog_post2_p1: "Bir dönem \"milli tank yapılamaz\" denilen bir ülkede, bugün KAAN göklerde, İHA'lar sınırlarımızda ve dünyanın dört bir yanında görev yapıyor. Peki bu başarıda en büyük zorluk neydi? Dışa bağımlı olduğumuz kritik alt bileşenlerin yerlileştirilmesi.",
        blog_post2_p2: "Megatech olarak vizyonumuz basit: Türkiye'nin savunma sanayiinde kullandığı her bir mekanik parçayı, artık yurt içinde üretebilmek.",
        blog_post2_h2_1: "Yerlileşme Yolculuğumuz:",
        blog_post2_li1: "Malzeme Tedariki: Özel alaşımlı çeliklerin yerli muadillerinin geliştirilmesi için TÜBİTAK MAM ile AR-GE projeleri.",
        blog_post2_li2: "Talaşlı İmalat: 5 eksenli işleme merkezlerinde, yurt dışından ithal edilen parçaların birebir aynısını, hatta daha dayanıklısını üretmek.",
        blog_post2_li3: "Isıl İşlem: Havacılık standartlarında (AMS, NADCAP) belgelendirilmiş fırınlarda, malzemenin iç yapısını optimize etmek.",
        blog_post2_p3: "Bugün, ASELSAN, ROKETSAN ve TUSAŞ'ın stratejik projelerinde yer alan Megatech, dışarıya akan dövizin önüne geçerek milli teknoloji hamlesine doğrudan katkı sunmaktadır.",
        blog_post3_title: "Yapay Zeka Destekli Hassas Üretim",
        blog_post3_excerpt: "Üretim hatlarımızda yapay zeka entegrasyonu ile hata payını sıfıra indiren yeni nesil kontrol sistemleri.",
        blog_post3_p1: "Savunma sanayiinde hata payı diye bir kavram yoktur. Bir vida dişindeki 0.01 mm'lik sapma, bir güdüm sisteminin tutarsız çalışmasına, dolayısıyla görevin başarısız olmasına yol açabilir. Megatech, bu riski sıfırlamak için üretim hatlarına yapay zekayı entegre etti.",
        blog_post3_h2_1: "Nasıl Çalışıyor?",
        blog_post3_p2: "Üretim tezgahlarımıza entegre edilen akustik emisyon sensörleri ve yüksek çözünürlüklü kameralar, her bir talaş kaldırma anını milisaniye düzeyinde analiz eder. Yapay zeka algoritmaları:",
        blog_post3_li1: "Kesici takımın aşınma seviyesini tahmin eder (Predictive Maintenance)",
        blog_post3_li2: "Anlık titreşim verilerini değerlendirip yüzey kalitesini öngörür.",
        blog_post3_li3: "Sapma tespit ettiğinde tezgahı otomatik olarak durdurur veya parametreleri düzeltir.",
        blog_post3_p3: "Sonuç: İnsan gözünün kaçırabileceği mikro çatlaklar veya yüzey bozuklukları, üretim anında tespit edilip raporlanır. Bu sayede müşterimize ulaşan her bir parçanın %100 kusursuz olduğundan emin oluyoruz. Geleceğin akıllı fabrikasını bugünden kuruyoruz.",
        blog_post4_title: "Havacılık ve Uzayda Yüksek Hassasiyet",
        blog_post4_excerpt: "Havacılık standartlarında parça üretiminde kalite kontrol ve tolerans yönetimi.",
        blog_post5_title: "Otonom Sistemler için Kritik Bileşenler",
        blog_post5_excerpt: "İHA ve kara otonom araçlarında kullanılan yüksek dayanımlı mekanik bileşenlerin üretimi.",
        blog_post6_title: "Savunmada Sürdürülebilir Kalite",
        blog_post6_excerpt: "Savunma sanayiinde uzun ömürlü ve güvenilir sistemler için malzeme seçimi ve ısıl işlem süreçleri.",
        blog_post7_title: "Milli Muharip Uçak ve Hassas Mühendislik",
        blog_post7_excerpt: "KAAN projesinde kullanılan ileri teknoloji parça imalat süreçlerine genel bakış.",
        blog_post8_title: "İHA ve SİHA Alt Sistem Üretimi",
        blog_post8_excerpt: "Türkiye'nin gururu İHA'lar için ürettiğimiz kritik mekanik aksamlar ve teknolojik detaylar.",
        blog_post9_title: "Zırhlı Araçlarda Mekanik Hassasiyet",
        blog_post9_excerpt: "Ağır zırhlı araç platformlarında dayanıklılık ve hassasiyet dengesi.",
        blog_post10_title: "Deniz Sistemlerinde Malzeme Mühendisliği",
        blog_post10_excerpt: "Denizaltı ve savaş gemileri için korozyona dayanıklı yüksek teknolojili parça üretimi.",
        blog_post11_title: "Roket ve Füze Sistemleri İmalatı",
        blog_post11_excerpt: "Yüksek hız ve sıcaklık dayanımı gerektiren füze bileşenlerinde ileri talaşlı imalat yöntemleri.",
        blog_post12_title: "Tıbbi Cihaz ve Savunma Teknolojileri",
        blog_post12_excerpt: "Medikal hassasiyetin savunma sanayiine aktarılması: İki sektör arasındaki mühendislik köprüsü.",
        blog_post13_title: "Endüstri 4.0 ve Savunma Entegrasyonu",
        blog_post13_excerpt: "Akıllı fabrikalar ve savunma sanayiinde dijital dönüşüm süreçleri.",
        blog_post14_title: "Savunma İhracatında Teknik Mükemmeliyet",
        blog_post14_excerpt: "Küresel pazarda Türk savunma sanayiinin rekabet gücü ve yüksek kalite standartları.",
        blog_post15_title: "Megatech Vizyon 2030",
        blog_post15_excerpt: "Geleceğin savunma teknolojilerinde Megatech'in stratejik hedefleri ve inovasyon rotası.",
        back_to_blog: "Bloğa Dön",
        blog_post4_p1: "Havacılık sektörü, tolerans kavramını yeniden tanımlamıştır. Bir uçak motoru fan kanadındaki 0.05 mm'lik kalınlık farkı, 30.000 feet irtibada metal yorgunluğuna ve felakete yol açabilir. Uzay sistemlerinde ise bu toleranslar nanometre seviyelerine iner.",
        blog_post4_h2_1: "Havacılıkta Hassas İmalat",
        blog_post4_p2: "Megatech olarak, AS9100D havacılık kalite yönetim sistemiyle belgelenmiş tesislerimizde şu kritik bileşenleri üretiyoruz:",
        blog_post4_li1: "Türbin Gövdeleri: 1000°C'nin üzerinde çalışan süper alaşımlardan (Inconel, Waspaloy) imalat.",
        blog_post4_li2: "Hidrolik Aktüatör Parçaları: Uçak iniş takımı ve kanat flapları için sıfır sızdırmazlık gerektiren hassas miller.",
        blog_post4_li3: "Enjeksiyon Sistemleri: Jet motorlarında yanma odasına yakıt püskürten mikro nozullar.",
        blog_post4_p3: "Her bir parça, üretim sonrası CMM (Koordinat Ölçüm Makinası) ve optik tarayıcılarla üç boyutlu olarak kontrol edilmekte, havacılık standartlarının en katı kriterlerine tabi tutulmaktadır. KAAN, HÜRJET ve GÖKBEY projelerinde bu hassasiyetin takipçisiyiz.",
        blog_post5_p1: "İHA, SİHA ve kara otonom araçları, savaşın doğasını değiştiriyor. Ancak bu sistemlerin kalbi, piller veya yazılımlar değil; hareket kabiliyetini sağlayan mekanik aktarma organlarıdır.",
        blog_post5_h2_1: "Otonom Platformlar için Kritik Bileşenler",
        blog_post5_p2: "Megatech, otonom platformlar için şu kritik bileşenleri geliştirmektedir:",
        blog_post5_li1: "Rulmanlı Yataklama Sistemleri: Yüksek hızlı dron motorları için 100.000 rpm devire dayanıklı seramik bilyalı rulmanlar.",
        blog_post5_li2: "Aktüatör Milleri: Elektro-mekanik aktüatörlerde 10.000 saat ömür testini geçen, aşınmaya dayanıklı karbür kaplamalı miller.",
        blog_post5_li3: "Redüktör Dişlileri: Yer otonom araçlarında yüksek tork gerektiren planet dişli sistemleri.",
        blog_post5_p3: "Türkiye'nin önde gelen İHA üreticilerine doğrudan tedarik sağlayan Megatech, bu bileşenlerin yurt dışı bağımlılığını ortadan kaldırarak milli otonom sistemlerin kesintisiz görev yapmasını garanti altına almaktadır.",
        blog_post6_p1: "Bir savaş uçağının ömrü 30-40 yıldır. Bu süre boyunca motoru defalarca revizyondan geçer, ancak gövde ve kritik yapısal parçalar değişmez. İşte burada \"sürdürülebilir kalite\" kavramı devreye girer: Bir parçanın sadece üretildiği gün değil, 30 yıl sonra da aynı performansı vermesi.",
        blog_post6_h2_1: "Megatech Kalite Felsefesi:",
        blog_post6_li1: "Malzeme Seçimi: 4340, 300M, 17-4 PH gibi yüksek dayanımlı çeliklerin yanı sıra havacılık sınıfı titanyum (Ti-6Al-4V) kullanımı.",
        blog_post6_li2: "Isıl İşlem Süreçleri: Vakum fırınlarında atmosfer kontrollü olarak uygulanan temperleme, söndürme ve kriyojenik işlemler.",
        blog_post6_li3: "Yüzey İşlemleri: Nikel kaplama, kadmiyum kaplama, veya havacılıkta tercih edilen pasivasyon ile korozyon direncinin maksimize edilmesi.",
        blog_post6_p2: "Megatech'ten çıkan her parça, zorlu çevre testlerinden (sıcaklık döngüsü, tuz sisi, titreşim) geçirilir. Kalite, bir başlangıç değil, bir bitiş noktasıdır.",
        blog_post7_p1: "KAAN, Türkiye'nin savunma sanayiinde geldiği noktanın somut bir göstergesidir. Bu proje, sadece bir uçak inşa etmekten ibaret değildir; aynı zamanda bir ülkenin hassas mühendislik kabiliyetinin testidir.",
        blog_post7_h2_1: "Milli Muharip Uçak ve Hassas Mühendislik",
        blog_post7_p2: "Megatech olarak KAAN projesindeki rolümüz, uçağın en kritik mekanik alt sistemlerinin imalatını kapsamaktadır:",
        blog_post7_li1: "Kokpit Güvenlik Kilidi Mekanizmaları: Pilotun binlerce km/s hızla giderken güvende kalmasını sağlayan, düşük ağırlıkta ve yüksek dayanımlı mekanizmalar.",
        blog_post7_li2: "Silah Yuvası Aktüatörleri: Gövde içine gizlenmiş güdümlü mühimmatların saniyeler içinde açılıp kapanmasını sağlayan hidrolik sistemler.",
        blog_post7_li3: "İniş Takımı Destek Elemanları: 20 tonun üzerindeki uçağın iniş anında yumuşak ve güvenli bir şekilde durmasını sağlayan şok emici parçalar.",
        blog_post7_p3: "Bu bileşenlerin her biri, 5 eksenli tezgahlarda, saatler süren işlemlerle blok malzemeden talaş kaldırılarak üretilmektedir. Her bir parçanın izlenebilirliği, üretimden montaja kadar dijital olarak kayıt altındadır.",
        blog_post8_p1: "Bayraktar TB2, AKINCI ve ANKA… Bu araçlar, Türkiye'nin gözbebeği olduğu kadar, dünya savunma literatürüne de geçmiş başarı hikayeleridir. Megatech, bu platformların görünmeyen kahramanı olan binlerce kritik alt bileşeni üretmektedir.",
        blog_post8_h2_1: "İHA ve SİHA Alt Sistem Üretimi",
        blog_post8_p2: "Ürettiğimiz kritik İHA bileşenleri:",
        blog_post8_li1: "Trim Aktüatör Gövdeleri: Uçağın uçuş yüzeylerini kontrol eden servo motorların ana gövdesi.",
        blog_post8_li2: "Yakıt Pompası Mili: Yüksek irtifa ve düşük sıcaklıkta dahi sorunsuz çalışan, aşınmaya dayanıklı özel tasarım mil.",
        blog_post8_li3: "Paraşüt Sistemi Mekanizması: İHA arızalandığında devreye giren paraşütün fırlatılmasını sağlayan piroteknik olmayan mekanik tetikleyiciler.",
        blog_post8_p3: "Megatech farkı: Bu parçaların tamamı, yerli sermaye ve yerli mühendislikle, yüksek adetli ve rekabetçi fiyatlarla üretilmekte ve Türk Silahlı Kuvvetleri'nin envanterine girmeden önce NATO standartlarında testlerden geçirilmektedir.",
        blog_post9_p1: "Zırhlı araçlar dendiğinde akla ilk gelen şey dayanıklılıktır. Doğrudur; bir Altay tankı 60 tonun üzerindedir ve doğrudan ateş altında görev yapar. Ancak bu ağırlığa rağmen bu araçların hareket kabiliyetini sağlayan mekanik sistemler, saatçi hassasiyeti gerektirir.",
        blog_post9_h2_1: "Zırhlı Araçlarda Mekanik Hassasiyet",
        blog_post9_p2: "Megatech'in zırhlı araç platformlarına katkısı:",
        blog_post9_li1: "Palet Pimleri ve Burçları: Tonlarca yük taşıyan palet sisteminin yıpranmadan yüzlerce saat görev yapmasını sağlayan yüksek karbonlu çelik pimler.",
        blog_post9_li2: "Taret Döndürme Redüktörü Dişlileri: Tank tareti 360 derece dönerken, topun darbeli geri tepmesine dayanabilen özel dişli geometrileri.",
        blog_post9_li3: "Şok Emici Silindirler: Engebeli arazide gövdeyi stabilize eden hidrolik ünitelerin honlanmış silindir iç yüzeyleri.",
        blog_post9_p3: "Tüm bu parçalar, milimetrik sapmaların aracın savaş kabiliyetini doğrudan etkileyebileceği bilinciyle, Megatech mühendisleri tarafından titizlikle işlenmektedir.",
        blog_post10_p1: "Tuzlu su, bir makine mühendisinin en büyük düşmanıdır. Denizaltı ve savaş gemileri, sürekli olarak korozyona maruz kalan, aynı zamanda derin basınç altında çalışan zorlu platformlardır. Megatech, deniz sistemleri için malzeme mühendisliğinin sınırlarını zorlamaktadır.",
        blog_post10_h2_1: "Korozyona Karşı Megatech Çözümleri",
        blog_post10_p2: "Deniz sistemleri için özel çözümlerimiz:",
        blog_post10_li1: "Şaft ve Pervane Göbekleri: Dubleks ve süper dubleks paslanmaz çeliklerden (Örn: 2205, 2507) üretim. Bu malzemeler, deniz suyunda oluşan klorür iyonlarına karşı üstün direnç gösterir.",
        blog_post10_li2: "Valfler ve Bağlantı Elemanları: Monel (nikel-bakır alaşımı) veya Hastelloy'dan imal edilen sızdırmazlık elemanları.",
        blog_post10_li3: "Kritik Cıvatalar: Havacılık sınıfı titanyum (Grade 5) veya yüzeyi nikel-kobalt kaplanmış yüksek dayanımlı çelikler.",
        blog_post10_p3: "Megatech, MİLGEM ve MİLDEN projelerine sağladığı bu özel alaşımlı parçalarla, Türk Deniz Kuvvetleri'nin mavi sularda uzun ömürlü ve güvenilir bir şekilde görev yapmasını desteklemektedir.",
        blog_post11_p1: "Bir füze fırlatıldığı andan itibaren, birkaç saniye içinde ses hızını aşar ve yüzlerce derecelik sıcaklıklara maruz kalır. Bu ortamda en ufak bir malzeme hatası, füzenin hedefe ulaşamadan infilak etmesine yol açar. Megatech, bu yüksek riskli üretimlerde güvenilir çözüm ortağıdır.",
        blog_post11_h2_1: "Roket ve Füze Sistemleri İmalatı",
        blog_post11_p2: "Üretim yelpazemiz:",
        blog_post11_li1: "Roket Motoru Gövdesi: Yüksek sıcaklık ve basınca dayanıklı, 15-5 PH paslanmaz çelikten hassas boru imalatı.",
        blog_post11_li2: "Nozul Tutucular: Yakıtın yanmasıyla oluşan aşındırıcı gazlara karşı özel seramik veya tungsten alaşımlı parçalar.",
        blog_post11_li3: "Güdüm Kanatçığı Mili: Füzenin yönlendirilmesini sağlayan küçük kanatçıkların, saniyede 40 derece dönüş yapmasını sağlayan hassas mil.",
        blog_post11_p3: "Tüm füze bileşenlerimiz, yurt dışı teknoloji lisansı olmadan, tamamen megatech mühendisliği ile geliştirilmekte ve ROKETSAN gibi lider kurumlarla yürütülen projelerde kullanılmaktadır.",
        blog_post12_p1: "İki sektör, ilk bakışta birbirinden çok uzak gibi görünür. Biri hayat kurtarır, diğeri korur. Ancak mühendislik altyapısına bakıldığında, tıbbi cihaz ve savunma teknolojileri arasında güçlü bir köprü vardır: Hassas talaşlı imalat.",
        blog_post12_h2_1: "Tıbbi Cihaz ve Savunma Teknolojileri Sinerjisi",
        blog_post12_p2: "Megatech, bu iki sektör arasındaki sinerjiyi en verimli şekilde kullanmaktadır:",
        blog_post12_li1: "Tıbbi Grade Kemik Vidası - Savunmadaki Muadili: Füze gövde bağlantı civatası",
        blog_post12_li2: "Cerrahi Alet (Paslanmaz 316L) - Savunmadaki Muadili: Denizaltı vana gövdeleri",
        blog_post12_li3: "İmplant Protez (Titanyum) - Savunmadaki Muadili: KAAN uçak gövde parçaları",
        blog_post12_p3: "Medikal sektörde kazandığımız nanometre seviyesindeki hassasiyet tecrübesi, savunma sanayiinde bize büyük avantaj sağlamaktadır. Savunma sanayiinde geliştirdiğimiz sağlam kalite kontrol sistemleri, tıbbi cihaz üretimimizin de temelini oluşturmaktadır.",
        blog_post13_p1: "Dördüncü sanayi devrimi, üretim tesislerini dönüştürmektedir. Artık sadece parça üreten fabrikalar değil; veri üreten, kendi kendini analiz eden ve optimize eden \"akıllı fabrikalar\" rekabet avantajı yaratmaktadır. Megatech, savunma sanayii özelinde Endüstri 4.0'ın tüm bileşenlerini devreye almıştır.",
        blog_post13_h2_1: "Megatech Akıllı Fabrika Bileşenleri",
        blog_post13_p2: "Endüstri 4.0 yaklaşımımız:",
        blog_post13_li1: "Nesnelerin İnterneti (IoT): Her tezgah, her ölçüm cihazı merkezi bir ağa bağlıdır. Üretim verileri anlık olarak izlenir.",
        blog_post13_li2: "Dijital İkiz (Digital Twin): Bir parça tezgaha bağlanmadan önce, simülasyon ortamında tüm işlem adımları test edilir, hatalar sanal ortamda ayıklanır.",
        blog_post13_li3: "ERP ve MES Entegrasyonu: Hammadde girişinden sevkiyata kadar her aşama, barkot ve RFID ile takip edilir. Müşteri, ürettirdiği parçasının nerede olduğunu anlık görebilir.",
        blog_post13_p3: "Bu dönüşümle Megatech, savunma sanayiinde sadece bir tedarikçi değil, aynı zamanda bir teknoloji çözüm ortağı konumuna yükselmiştir.",
        blog_post14_p1: "Türk savunma sanayii, son 10 yılda sadece kendi ihtiyacını karşılamakla kalmadı, dünyanın en büyük ihracatçılarından biri haline geldi. Bu başarının arkasındaki en büyük güç, Megatech gibi KOBİ seviyesindeki yüksek teknoloji üretim merkezleridir.",
        blog_post14_h2_1: "Savunma İhracatında Teknik Mükemmeliyet",
        blog_post14_p2: "Dünya pazarında nasıl rekabet ediyoruz?",
        blog_post14_li1: "Sertifikasyon Gücü: AS9100D ve ISO 9001:2015 belgelerimizle, Avrupa ve Orta Doğu'daki dev savunma firmalarının onaylı tedarikçisiyiz.",
        blog_post14_li2: "Maliyet ve Verimlilik: CNC kayar otomat teknolojisiyle, geleneksel yöntemlere göre %40 daha hızlı ve daha az fire ile üretim yaparak rekabetçi fiyatlar sunuyoruz.",
        blog_post14_li3: "Zamanında Teslimat: Gelişmiş üretim planlama yazılımlarımızla, kritik projelerde gecikmeye yer vermiyoruz.",
        blog_post14_p3: "Megatech olarak, ihraç edilen her bir parçanın üzerinde \"Made in Türkiye\" damgasını gururla taşıyor ve Türk mühendisliğinin kalitesini dünyaya kanıtlıyoruz.",
        blog_post15_p1: "2030'a doğru bakarken Megatech, savunma teknolojisinin en uç noktasında kalmaya kararlıdır. Yol haritamız, yeteneklerimizi genişletmeye ve yeni nesil inovasyonları benimsemeye odaklanmaktadır.",
        blog_post15_h2_1: "İnovasyon Üzerine İnşa Edilen Bir Gelecek",
        blog_post15_p2: "Yapay zekanın daha derin entegrasyonundan yeni kompozit malzemelerin keşfine kadar gelecek vizyonumuz, ortaklarımızın en karmaşık mühendislik zorluklarını çözme arzusuyla şekillenmektedir. Sadece parça üretmiyoruz; güvenliğin geleceğini inşa ediyoruz."
    }
};

let currentLang = 'tr';

function toggleLanguage() {
    currentLang = currentLang === 'en' ? 'tr' : 'en';
    updateContent();
    document.getElementById('lang-toggle').innerText = currentLang === 'en' ? 'TR' : 'EN';
    document.documentElement.setAttribute('lang', currentLang);
    localStorage.setItem('preferredLang', currentLang);
}

function updateContent() {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key];
        }
    });

    const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
    placeholders.forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[currentLang][key]) {
            el.setAttribute('placeholder', translations[currentLang][key]);
        }
    });
}

document.getElementById('lang-toggle').addEventListener('click', toggleLanguage);

// Mobile Menu Toggle
const mobileMenu = document.getElementById('mobile-menu');
const navLinks = document.querySelector('.nav-links');

if (mobileMenu) {
    mobileMenu.addEventListener('click', () => {
        mobileMenu.classList.toggle('active');
        navLinks.classList.toggle('active');
    });
}

// Close menu when a link is clicked
document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', () => {
        if (mobileMenu) {
            mobileMenu.classList.remove('active');
            navLinks.classList.remove('active');
        }
    });
});

// Initialize with preferred language or default to 'tr'
window.onload = () => {
    const savedLang = localStorage.getItem('preferredLang');
    const version = localStorage.getItem('siteVersion');
    const currentVersion = '1.1'; // Increment this to force a language reset if needed

    if (version !== currentVersion) {
        // First time visiting this version, default to Turkish and clear old preference
        currentLang = 'tr';
        localStorage.setItem('preferredLang', 'tr');
        localStorage.setItem('siteVersion', currentVersion);
        updateContent();
        document.getElementById('lang-toggle').innerText = 'EN';
        document.documentElement.setAttribute('lang', 'tr');
    } else if (savedLang) {
        currentLang = savedLang;
        updateContent();
        document.getElementById('lang-toggle').innerText = currentLang === 'en' ? 'TR' : 'EN';
        document.documentElement.setAttribute('lang', currentLang);
    } else {
        // Ensure the button text and content match the default 'tr'
        currentLang = 'tr';
        updateContent();
        document.getElementById('lang-toggle').innerText = 'EN';
        document.documentElement.setAttribute('lang', 'tr');
    }
};
