const translations = {
    en: {
        nav_capabilities: "Capabilities",
        nav_innovation: "Innovation",
        nav_about: "About Us",
        nav_contact: "Contact",
        hero_title: 'Defense Technologies <br>of the <span class="logo-accent">Future</span>',
        hero_subtitle: "Shaping global security through next-generation high-precision production solutions.",
        btn_explore: "Explore",
        btn_contact: "Contact",
        about_title: "About Us",
        about_p1: "Megatech Defense is an innovative engineering firm offering high-precision production solutions in CNC sliding head machine technologies.",
        about_p2: "We specialize in manufacturing precision parts for mission-critical sectors, including defense, automotive, aerospace, medical, and industrial production.",
        about_p3: "Leveraging our state-of-the-art CNC sliding head machinery and robust infrastructure, we produce components with complex geometries to the highest quality standards. Our serial production processes are engineered for reliability, ensuring dimensional precision and customer satisfaction at every stage.",
        about_p4: "Our mission is to integrate advanced technology with superior engineering and precision manufacturing, delivering the reliable solutions our industry demands while maintaining a commitment to sustainable quality.",
        exp_text: "Years of Experience",
        innovation_title: "Innovation",
        inn_card1_title: "AI-Powered Precision",
        inn_card1_desc: "Integrating advanced artificial intelligence to optimize CNC processes and ensure zero-defect manufacturing.",
        inn_card2_title: "Autonomous Systems",
        inn_card2_desc: "Developing high-precision components for the next generation of land, air, and sea autonomous defense platforms.",
        inn_card3_title: "Tactical Materials",
        inn_card3_desc: "Expertise in working with advanced aerospace-grade alloys and composites for mission-critical applications.",
        contact_title: "Contact Us",
        contact_h3: "Get in Touch",
        contact_desc: "Our team of experts is ready to discuss your high-precision manufacturing requirements.",
        info_email: "Email:",
        info_location: "Location:",
        info_phone: "Phone:",
        placeholder_name: "Your Name",
        placeholder_email: "Your Email",
        placeholder_subject: "Subject",
        placeholder_message: "Your Message",
        btn_send: "Send Message",
        footer_desc: "Leading the way in advanced defense technologies, aerospace engineering, and tactical systems. Engineering the future of global security.",
        footer_capabilities: "CAPABILITIES",
        footer_resources: "QUICK LINKS",
        footer_contact: "CONTACT",
        link_aerospace: "Aerospace Systems",
        link_naval: "Naval Engineering",
        link_land: "Land Defense",
        link_cyber: "Cyber Security",
        link_docs: "Technical Docs",
        link_career: "Career Portal",
        link_press: "Press Room",
        link_sustainability: "Sustainability",
        footer_location: "Saray Mahallesi, 30. Cd. 15B 06980 Kahramankazan Ankara, Türkiye",
        footer_rights: "All rights reserved.",
        link_privacy: "Privacy Policy",
        link_terms: "Terms of Use & KVKK",
        contact_page_title: 'Contact Our <span class="logo-accent">Experts</span>',
        contact_page_subtitle: "We are ready to provide the precision engineering solutions your project requires.",
        contact_desc_dedicated: "Reach out to our engineering team directly for technical inquiries or quote requests.",
        info_office: "Corporate Office:",
        office_location: "Saray Mahallesi, 30. Cd. 15B<br>06980 Kahramankazan Ankara<br>Türkiye",
        label_name: "Full Name",
        label_email: "Email Address",
        label_sector: "Industry Sector",
        label_message: "Your Message",
        placeholder_name_val: "John Doe",
        placeholder_email_val: "john@example.com",
        placeholder_message_val: "Describe your project requirements...",
        btn_send_secure: "Contact Our Team",
        nav_blog: "BLOG",
        blog_title: "Defense Industry & Technology Blog",
        blog_subtitle: "Insights into the future of precision manufacturing and defense tech.",
        read_more: "Read More",
        blog_post1_title: "Role of CNC Sliding Head Technology in Defense",
        blog_post1_excerpt: "Critical importance of CNC sliding head machines in micro-precision parts for modern defense platforms.",
        blog_post1_p1: "In the defense industry, every single component is of vital importance. The guidance system of a missile, the engine block of a UAV, or the transmission gear of an armored vehicle... All of these parts must be produced with micro-meter level precision. This is exactly where CNC sliding head technology comes into play. CNC sliding head machines are the pinnacle of small-part precision, offering capabilities that traditional lathes simply cannot match. At Megatech, we utilize these machines to produce the most demanding components for Turkey's national defense projects.",
        blog_post1_h2_1: "Why CNC Sliding Head in Defense?",
        blog_post1_p2: "Unlike traditional lathes, sliding heads work on a principle where the material moves axially while the tool remains relatively stationary, supported by a guide bushing. This method offers several key advantages for defense platforms:",
        blog_post1_li1: "Unrivaled Roundness Precision: Achieving tolerances as low as 0.002 mm, which is critical for rotating parts in high-speed turbines.",
        blog_post1_li2: "High Surface Quality: Achieving Ra 0.2 μm surface finish, reducing friction and wear in hydraulic systems.",
        blog_post1_li3: "High-Speed Capability: With spindles reaching 12,000 RPM, we can process tough materials like titanium and stainless steel with extreme efficiency.",
        blog_post1_h2_2: "Advanced Applications and Material Complexity",
        blog_post1_p3: "Modern defense systems require parts that are not only small but also extremely complex in geometry. Our CNC sliding head machines feature up to 10 axes of movement, allowing us to perform milling, drilling, and tapping operations in a single setup. This 'done-in-one' philosophy eliminates setup errors and ensures perfect concentricity between features.",
        blog_post1_p4: "We process a wide range of exotic materials, including Inconel, Monel, and aerospace-grade Titanium. These materials are notoriously difficult to machine due to their hardness and heat resistance. However, our specialized cooling systems and high-pressure oil delivery ensure that tool wear is minimized and part integrity is maintained throughout the production cycle.",
        blog_post1_h2_3: "The Megatech Standard of Excellence",
        blog_post1_p5: "Every part produced at Megatech undergoes a multi-stage inspection process. We utilize automated optical inspection (AOI) systems directly integrated into our CNC cells to monitor part quality in real-time. This proactive approach ensures that our zero-defect policy is not just a slogan, but a technical reality.",
        blog_post1_p6: "By investing in the latest Japanese and German CNC technologies, we provide the Turkish defense industry with a reliable, local source for components that were previously imported. This strengthens our national security and ensures that our defense platforms are built with the highest quality parts available.",
        blog_post2_title: "Localization in Turkish Defense & Megatech",
        blog_post2_excerpt: "Our local production solutions and engineering vision reducing foreign dependency in national projects.",
        blog_post2_p1: "In an era where national defense is synonymous with technological sovereignty, the localization of critical components is no longer an option—it is a necessity. Turkey has made incredible strides in the last decade, with projects like KAAN, TCG Anadolu, and various UAV platforms. However, the true success of these projects lies in the sub-systems and components produced by local engineering firms like Megatech.",
        blog_post2_p2: "At Megatech, our vision is simple: to ensure that every mechanical component used in Turkey's defense platforms can be designed, engineered, and manufactured within our borders. This mission drives our R&D investments and our commitment to technical excellence.",
        blog_post2_h2_1: "Our Localization Roadmap",
        blog_post2_li1: "Material Sovereignty: We collaborate with local material scientists to develop domestic alternatives to specialty aerospace steels, ensuring our supply chain is resilient to international sanctions.",
        blog_post2_li2: "Precision Machining: By utilizing 5-axis machining centers and sliding head technology, we reproduce complex parts that were previously only available from foreign OEMs, often improving their design and durability.",
        blog_post2_li3: "Advanced Heat Treatment: We employ NADCAP-certified heat treatment processes to optimize the molecular structure of the metals we work with, ensuring they meet the extreme stress requirements of defense applications.",
        blog_post2_h2_2: "Strategic Impact on National Projects",
        blog_post2_p3: "Our contribution to projects like ASELSAN's radar systems and ROKETSAN's missile guidance units has directly reduced foreign dependency. By producing these parts locally, we not only save millions in foreign exchange but also gain the flexibility to modify and improve designs without waiting for foreign approvals.",
        blog_post2_p4: "Localization also means faster turnaround times. In the fast-paced world of defense, the ability to iterate on a design and produce a prototype within days rather than months is a significant tactical advantage. Megatech's agile manufacturing processes are designed to support this rapid development cycle.",
        blog_post2_h2_3: "Building the Future of Turkish Engineering",
        blog_post2_p5: "We are not just a manufacturer; we are a training ground for the next generation of Turkish engineers. By working on high-tech projects, our team develops skills in CAD/CAM, material science, and precision metrology that are vital for the country's industrial future.",
        blog_post3_title: "AI-Powered Precision Manufacturing",
        blog_post3_excerpt: "Next-generation control systems eliminating error rates with AI integration in our production lines.",
        blog_post3_p1: "The defense industry has no room for error. A deviation of 0.01 mm in a screw thread can lead to a guidance system failure, resulting in mission catastrophe. To eliminate this risk, Megatech has integrated advanced Artificial Intelligence (AI) into its production lines, moving beyond traditional automation into the realm of intelligent manufacturing.",
        blog_post3_p2: "AI at Megatech is not just about robots; it's about data. Every machine on our floor is part of a connected ecosystem that constantly feeds data into our centralized AI engine, which analyzes performance in real-time.",
        blog_post3_h2_1: "How AI Enhances Precision",
        blog_post3_p3: "We utilize acoustic emission sensors and high-resolution cameras integrated into our CNC machines. These sensors capture data at the millisecond level, allowing our AI algorithms to:",
        blog_post3_li1: "Predict Tool Wear: The AI analyzes the sound and vibration patterns of the cutting process to predict when a tool will fail before it happens, allowing for proactive replacement without part damage.",
        blog_post3_li2: "Real-time Surface Analysis: High-speed cameras monitor the surface finish of the parts as they are being machined, identifying micro-cracks or irregularities that the human eye would miss.",
        blog_post3_li3: "Adaptive Process Control: If the AI detects a slight deviation in material hardness or temperature, it automatically adjusts the machine's feed rate and spindle speed to maintain perfect precision.",
        blog_post3_h2_2: "The Path to Zero-Defect Manufacturing",
        blog_post3_p4: "Traditional quality control happens after the part is made. With AI, quality control happens *while* the part is being made. This shift from reactive to proactive monitoring is the cornerstone of our zero-defect policy. It ensures that 100% of the parts that leave our facility meet the exact specifications of our partners.",
        blog_post3_p5: "Furthermore, our AI systems help us optimize material usage. By predicting exactly how much material is needed for each part and reducing scrap, we not only lower costs for our partners but also minimize our environmental footprint.",
        blog_post3_h2_3: "The Future: Self-Optimizing Factories",
        blog_post3_p6: "Our ultimate goal is the creation of a fully self-optimizing factory. In this vision, the machines will not only monitor themselves but also learn from every part they produce, constantly improving efficiency and precision. Megatech is proud to be at the forefront of this Industry 4.0 revolution in Turkey.",
        blog_post4_title: "High-Precision in Aerospace",
        blog_post4_excerpt: "Quality control and tolerance management in aerospace-grade part manufacturing.",
        blog_post5_title: "Critical Components for Autonomous Systems",
        blog_post5_excerpt: "Manufacturing high-strength mechanical components for UAVs and land autonomous vehicles.",
        blog_post6_title: "Sustainable Quality in Defense",
        blog_post6_excerpt: "Material selection and heat treatment processes for reliable and long-lasting defense systems.",
        blog_post7_title: "National Combat Aircraft & Precision Engineering",
        blog_post7_excerpt: "Overview of high-tech part manufacturing processes for the KAAN project.",
        blog_post8_title: "UAV & UCAV Subsystem Manufacturing",
        blog_post8_excerpt: "Critical mechanical parts and technological details for Turkey's pride, the UAVs.",
        blog_post9_title: "Mechanical Precision in Armored Vehicles",
        blog_post9_excerpt: "Balancing durability and precision in heavy armored vehicle platforms.",
        blog_post10_title: "Material Engineering in Naval Systems",
        blog_post10_excerpt: "Corrosion-resistant high-tech part production for submarines and warships.",
        blog_post11_title: "Rocket & Missile Systems Manufacturing",
        blog_post11_excerpt: "Advanced machining methods for missile components requiring high speed and temperature resistance.",
        blog_post12_title: "Medical Device & Defense Technology Synergy",
        blog_post12_excerpt: "Transferring medical precision to defense: An engineering bridge between two sectors.",
        blog_post13_title: "Industry 4.0 & Defense Integration",
        blog_post13_excerpt: "Smart factories and digital transformation processes in the defense industry.",
        blog_post14_title: "Technical Excellence in Defense Exports",
        blog_post14_excerpt: "Competitive power and high quality standards of the Turkish defense industry in global markets.",
        blog_post15_title: "Megatech Vision 2030",
        blog_post15_excerpt: "Megatech's strategic goals and innovation roadmap in future defense technologies.",
        back_to_blog: "Back to Blog",
        open_in_maps: "Open in Maps",
        blog_post4_p1: "The aerospace sector has redefined the concept of tolerance. A 0.05 mm thickness difference in an aircraft engine fan blade can lead to metal fatigue and disaster at 30,000 feet. In space systems, these tolerances drop to nanometer levels.",
        blog_post4_h2_1: "Precision Manufacturing in Aerospace",
        blog_post4_p2: "At our facilities certified with the AS9100D aerospace quality management system, we produce these critical components:",
        blog_post4_li1: "Turbine Housings: Manufacturing from superalloys (Inconel, Waspaloy) operating above 1000°C.",
        blog_post4_li2: "Hydraulic Actuator Parts: Precision shafts requiring zero leakage for aircraft landing gear and wing flaps.",
        blog_post4_li3: "Injection Systems: Micro nozzles that spray fuel into the combustion chamber in jet engines.",
        blog_post4_p3: "Every part is three-dimensionally controlled post-production with CMM (Coordinate Measuring Machine) and optical scanners, and subjected to the strictest criteria of aerospace standards. We follow this precision in the KAAN, HÜRJET, and GÖKBEY projects.",
        blog_post5_p1: "Autonomous systems like UAVs, UCAVs, and unmanned ground vehicles are changing the nature of warfare. However, the heart of these systems is not batteries or software; it's the mechanical power transmission organs that provide mobility.",
        blog_post5_h2_1: "Critical Components for Autonomous Platforms",
        blog_post5_p2: "Megatech develops these critical components for autonomous platforms:",
        blog_post5_li1: "Ball Bearing Systems: Ceramic ball bearings resistant to 100,000 rpm for high-speed drone motors.",
        blog_post5_li2: "Actuator Shafts: Wear-resistant carbide-coated shafts that pass the 10,000-hour life test in electro-mechanical actuators.",
        blog_post5_li3: "Reducer Gears: Planetary gear systems requiring high torque in ground autonomous vehicles.",
        blog_post5_p3: "Providing direct supply to Turkey's leading UAV manufacturers, Megatech guarantees the uninterrupted mission of national autonomous systems by eliminating foreign dependency on these components.",
        blog_post6_p1: "The life of a fighter jet is 30-40 years. During this time, its engine is overhauled many times, but the fuselage and critical structural parts do not change. This is where 'sustainable quality' comes in: A part performing just as well 30 years later as it did the day it was produced.",
        blog_post6_h2_1: "Megatech Quality Philosophy:",
        blog_post6_li1: "Material Selection: Use of aerospace-grade titanium (Ti-6Al-4V) as well as high-strength steels like 4340, 300M, 17-4 PH.",
        blog_post6_li2: "Heat Treatment Processes: Tempering, quenching, and cryogenic processes applied under atmospheric control in vacuum furnaces.",
        blog_post6_li3: "Surface Treatments: Maximizing corrosion resistance with nickel plating, cadmium plating, or passivation preferred in aerospace.",
        blog_post6_p2: "Every part coming out of Megatech is subjected to rigorous environmental tests (temperature cycle, salt fog, vibration). Quality is not a starting point, but an end point.",
        blog_post7_p1: "KAAN is a concrete indicator of the point Turkey has reached in the defense industry. This project is not just about building an aircraft; it is also a test of a country's precision engineering capability. A 5th generation fighter jet requires the perfect harmony of thousands of micro and macro parts for radar invisibility (stealth) and high maneuverability.",
        blog_post7_p2: "As Megatech, our role in the KAAN project covers the manufacture of the aircraft's most critical mechanical subsystems. These parts ensure the fuselage integrity and operational safety of the aircraft.",
        blog_post7_h2_1: "National Combat Aircraft and Precision Engineering Applications",
        blog_post7_li1: "Cockpit Safety Lock Mechanisms: Low-weight and extremely high-strength titanium mechanisms that ensure the pilot stays safe while traveling at thousands of km/h and under high G-force.",
        blog_post7_li2: "Weapon Bay Actuators: Precision hydraulic and mechanical systems that allow munitions hidden inside the fuselage for radar invisibility to open and close within seconds.",
        blog_post7_li3: "Landing Gear Support Elements: Special heat-treated steel parts that absorb the massive impact loads the aircraft over 20 tons is exposed to at the moment of landing.",
        blog_post7_h2_2: "Machining from Block Material (Monolithic Structures)",
        blog_post7_p3: "In aerospace, machining parts from a single block material (monolithic manufacturing) instead of joining parts eliminates structural weaknesses. Megatech contributes to KAAN's light and durable fuselage structure by processing large blocks with micron precision with 5-axis CNC technology.",
        blog_post7_p4: "Each of these components is digitally recorded from production to assembly. Every micron deviation is reported and full traceability of each process step on the part is guaranteed.",
        blog_post8_p1: "Bayraktar TB2, AKINCI, and ANKA... These vehicles are success stories that have changed the world defense literature as much as they are Turkey's pride. The success of these UAVs depends not only on their software but also on their mechanical subcomponents that work without failure for thousands of hours.",
        blog_post8_p2: "Megatech produces thousands of critical subcomponents that are the unseen heroes of these platforms. From the engine to the fins of a UAV, there is Megatech's precision touch at every point.",
        blog_post8_h2_1: "UAV and UCAV Subsystem Production and Technological Details",
        blog_post8_li1: "Trim Actuator Bodies: The main body of the servo motors controlling the aircraft's flight surfaces (fins). Perfect surface quality for aerodynamic resistance.",
        blog_post8_li2: "Fuel Pump Shafts: Special design shafts resistant to wear and cold that provide uninterrupted fuel flow even at 30,000 feet altitude and -50°C temperature.",
        blog_post8_li3: "Parachute System Mechanisms: Non-pyrotechnic but instantly reacting mechanical triggers that allow the parachute protecting the UAV in emergencies to be launched.",
        blog_post8_h2_2: "Reliability in NATO Standards",
        blog_post8_p3: "The Megatech difference: All of these parts are produced with local capital and local engineering, in high volumes and at world-standard competitive prices. Every batch produced enters the inventory by passing tests in NATO (STANAG) standards.",
        blog_post8_p4: "While we increase our localization rate every passing day, we are taking firm steps towards being a critical part supplier not only for Turkey but also for the UAV fleets of friendly and allied countries.",
        blog_post9_p1: "When armored vehicles are mentioned, the first thing that comes to mind is a rough durability. However, an Altay tank or a Pars armored vehicle is not just made of thick armor plates. The mechanical systems that provide the mobility and firepower of these vehicles are actually as precise as a clockwork.",
        blog_post9_p2: "Megatech produces mechanical engineering solutions that ensure armored vehicles work smoothly in the most demanding terrain conditions and at the moment of conflict. We are at the intersection of durability and precision.",
        blog_post9_h2_1: "Mechanical Precision and Operational Safety in Armored Vehicles",
        blog_post9_li1: "Track Pins and Bushings: Pins with special surface hardening techniques applied that carry the 60-ton load and resist wear for kilometers of road.",
        blog_post9_li2: "Turret Rotation Reducer Gears: Special gear geometries that can withstand the impulsive recoil strike of the main weapon while the tank turret rotates 360 degrees in seconds.",
        blog_post9_li3: "Suspension and Shock Absorber Cylinders: Micron-level honed inner surfaces of hydraulic units that maintain speed on rugged terrain.",
        blog_post9_h2_2: "Recoil and Impact Engineering",
        blog_post9_p3: "The impulsive forces generated during the firing of large-caliber weapons test all mechanical parts of the vehicle. As Megatech, we design and produce parts resistant to these shock waves with high fatigue life.",
        blog_post9_p4: "All of these parts are meticulously processed on the most modern CNC machines by Megatech engineers, with the awareness that millimetric deviations can directly affect the combat capability of the vehicle.",
        blog_post10_p1: "Salt water is a mechanical engineer's worst enemy. Submarines and warships are not only constantly exposed to corrosion but are also the world's most challenging mechanical platforms operating under deep sea pressure and variable thermal loads. Megatech offers material engineering solutions that can withstand these demanding conditions.",
        blog_post10_p2: "Parts used in naval systems can cause the onset of corrosion (pitting) even at the slightest surface defect. Therefore, post-manufacturing surface quality and material selection are of vital importance.",
        blog_post10_h2_1: "Megatech Solutions Against Corrosion and Submarine Technologies",
        blog_post10_li1: "Shaft and Propeller Hubs: Production from duplex and super duplex stainless steels (e.g., 2205, 2507). These materials show superior resistance to chloride ions found in seawater and high mechanical strength.",
        blog_post10_li2: "Sealing Elements and Valves: Critical parts manufactured from Monel (nickel-copper alloy) or Hastelloy that do not lose their sealing property even under deep sea pressure.",
        blog_post10_li3: "Critical Fasteners: Aerospace-grade titanium (Grade 5) or high-tensile strength special bolts with surface coated with nickel-cobalt and extended corrosion life.",
        blog_post10_h2_2: "Contribution to MİLGEM and MİLDEN Projects",
        blog_post10_p3: "Megatech is a strategic supplier in Turkey's national ship (MİLGEM) and national submarine (MİLDEN) projects. We produce ultra-precision tolerance propulsion system components necessary for submarines to perform silent cruising, with the most modern machining methods.",
        blog_post10_p4: "We continue to push the boundaries of material science so that our platforms serving in the defense of the Blue Homeland can perform their duties for decades without experiencing corrosion problems.",
        blog_post11_p1: "From the moment a missile is launched, it reaches multiples of the speed of sound (Mach speeds) within a few seconds and is exposed to temperatures of hundreds of degrees due to atmospheric friction. In this extreme environment, every detail from the expansion coefficient of the part to the internal structure integrity determines whether the missile will hit the target.",
        blog_post11_p2: "Megatech is a solution partner specialized in high-risk and high-precision production for rocket and missile systems. Every component we produce is a part of the deterrent power of our national defense.",
        blog_post11_h2_1: "Rocket and Missile Systems Manufacturing and Thermal Resistance Engineering",
        blog_post11_li1: "Rocket Engine Bodies: Precision tube and body manufacturing from 15-5 PH or 17-4 PH stainless steels, resistant to high internal pressure and thermal shock.",
        blog_post11_li2: "Nozzle Holders and Gas Directors: Special ceramic or tungsten alloy components resistant to corrosive and super-hot gases formed by fuel combustion.",
        blog_post11_li3: "Guidance Fin Drive Shafts: Precision mechanical shafts that allow the missile to maneuver in the air, react within milliseconds, and carry high torque.",
        blog_post11_h2_2: "ROKETSAN and the National Missile Family",
        blog_post11_p3: "In projects we carry out with world-giant institutions like ROKETSAN, we produce critical parts of our domestic missiles (HİSAR, SİPER, ATMACA). X-ray and ultrasonic tests we apply on these parts guarantee that no invisible defect remains in the material.",
        blog_post11_p4: "Our precision machining capability ensures that rocket systems are not only durable but also exhibit perfect aerodynamic stability while heading towards the target.",
        blog_post12_p1: "Although medical device production and the defense industry seem opposite at first glance, both are based on the same principle on the engineering basis: Precision without a margin for error. A bone screw used by a surgeon and a fuselage bolt of a missile actually have similar tolerance and material requirements.",
        blog_post12_p2: "Megatech has created a unique production synergy by blending its nanometer-level precision experience in the medical sector with the robustness requirements of the defense industry.",
        blog_post12_h2_1: "Engineering Bridge Between Medical Device and Defense Technologies",
        blog_post12_li1: "Material Similarity: Titanium Grade 5 used in medical implants is the most ideal material for aircraft fuselage parts in the defense industry. Biocompatibility or corrosion resistance is essential in both areas.",
        blog_post12_li2: "Quality Systems Integration: The similarity between ISO 13485 (Medical) and AS9100D (Defense) standards ensures that our production lines are auditable at the highest level for both sectors.",
        blog_post12_li3: "Micro-Machining Capability: We transfer our precision in micro-gears we produce for surgical robotic arms to the camera stabilization systems (gimbals) of UAVs.",
        blog_post12_h2_2: "Cross-Sector Knowledge Transfer",
        blog_post12_p3: "The extreme clean production and smooth surface standards required by the medical sector increase the fatigue life of our parts in the defense industry. The high-strength machining techniques we developed in the defense industry ensure that our medical devices are more durable.",
        blog_post12_p4: "As Megatech, with this interdisciplinary approach, we do not limit innovation to just one sector, we increase Turkey's technological competence in both areas.",
        blog_post13_p1: "The fourth industrial revolution (Industry 4.0) is transforming production facilities from static structures into living, learning, and evolving ecosystems. In a sector like the defense industry where error tolerance is zero, this digital transformation is not just a productivity tool, but also a source of strategic superiority.",
        blog_post13_p2: "Megatech has fully implemented the 'Smart Factory' concept by connecting every CNC machine, measuring device, and personnel terminal on the production line to a single digital nervous system.",
        blog_post13_h2_1: "Megatech Smart Factory Components and Digital Transformation",
        blog_post13_li1: "IoT and Live Monitoring: Instant data from every machine (feed rates, tool loads, energy consumption) is analyzed in a central cloud system. In this way, production bottlenecks are identified before they occur.",
        blog_post13_li2: "Digital Twin: A virtual model is first created for each part to be produced. Cutting strategies are tested on this virtual model, and collisions or errors that may occur on the actual machine are 100% prevented.",
        blog_post13_li3: "MES and Full Traceability: Every raw material leaving the material warehouse gains a digital identity (RFID/Barcode). Our customer can track instantly on which machine, by which operator, and with what precision their order is processed.",
        blog_post13_h2_2: "Data-Driven Decision Support Mechanisms",
        blog_post13_p3: "Our AI-powered algorithms recommend the most optimized machining parameters for future projects by analyzing past production data. This allows us to create 'corporate memory' and start every new project one step ahead.",
        blog_post13_p4: "As Megatech, we do not see Industry 4.0 only as buying technology, but as adapting our production culture to the digital age.",
        blog_post14_p1: "The Turkish defense industry has broken its shell in the last decade and become a global player. Today, there is a Turkey that not only meets its own needs but exports technology to the world. Megatech is one of the hidden powers behind this export success: High technology and excellence at the SME level.",
        blog_post14_p2: "To compete with global giants (like Lockheed Martin, Airbus, Boeing), being 'cheap' is not enough; you must be 'the best' and 'the most reliable'. Megatech's export strategy is built exactly on this excellence.",
        blog_post14_h2_1: "The Signature of Turkish Engineering in the Global Market",
        blog_post14_li1: "Certification Power: Our AS9100D Aerospace and Defense Quality Management System certification ensures that our parts are accepted as 'flight-ready' anywhere in the world. This is our passport to entry into global supply chains.",
        blog_post14_li2: "CNC Sliding Head Expertise: We offer the best cost-quality ratio in the world in the production of complex and small parts. We get ahead of our competitors by producing 40% faster than traditional methods.",
        blog_post14_li3: "Cultural Adaptation and Fast Return: We understand the technical languages and standards (DIN, ANSI, MIL-SPEC) of our business partners in different countries and respond to prototype requests within days.",
        blog_post14_h2_2: "Technology Ambassadorship",
        blog_post14_p3: "Every single part we export is actually a business card of Turkish engineering. As Megatech, we are proud to be part of critical projects in a wide geography from Europe to the Middle East and to increase Turkey's technological reputation.",
        blog_post15_p1: "For Megatech, the future is a journey built on yesterday's successes but pushing today's limits. Our 'Vision 2030' plan aims to take our company beyond being just a manufacturer and turn it into a world-class 'Advanced Manufacturing Technologies Center'.",
        blog_post15_p2: "The next decade will witness radical changes in manufacturing technologies. Megatech intends to be the driver, not the follower, of this change.",
        blog_post15_h2_1: "Megatech Vision 2030: Roadmap to the Future",
        blog_post15_li1: "Fully Autonomous Production: Our goal is to make 90% of our production lines operational without human intervention by 2030, working 24/7 with the lights-out manufacturing concept.",
        blog_post15_li2: "Nanotechnology and Next-Generation Materials: We are establishing our R&D laboratories to become a world leader in the processing of graphene-reinforced composites and ultra-light magnesium alloys.",
        blog_post15_li3: "Sustainability and Green Defense: By meeting 100% of our production facility's energy needs from renewable sources, we will be the pioneer of 'Green Defense Manufacturing' with zero carbon footprint.",
        blog_post15_h2_2: "Global Engineering Network",
        blog_post15_p3: "We will make Megatech a world brand by supporting our Ankara-based production with design and engineering offices we will open in Europe and America. We are not just making parts; we are building the future of global security.",
        blog_post15_p4: "The future belongs to those who design it today. Be ready for this future with Megatech.",
    },
    tr: {
        nav_capabilities: "YETENEKLER",
        nav_innovation: "İNOVASYON",
        nav_about: "HAKKIMIZDA",
        nav_blog: "BLOG",
        nav_contact: "İLETİŞİM",
        hero_title: 'GELECEĞİN SAVUNMA <br><span class="logo-accent">TEKNOLOJİLERİ</span>',
        hero_subtitle: "Yüksek hassasiyetli üretim çözümleri ile global güvenliğe yön veriyoruz.",
        btn_explore: "KEŞFEDİN",
        btn_contact: "İLETİŞİM",
        about_title: "HAKKIMIZDA",
        about_p1: "Megatech Savunma, CNC kayar otomat işleme teknolojilerinde yüksek hassasiyetli üretim çözümleri sunan yenilikçi bir mühendislik firmasıdır.",
        about_p2: "Savunma sanayi başta olmak üzere otomotiv, havacılık, medikal ve endüstriyel üretim sektörlerine yönelik hassas parça imalatı gerçekleştirmektedir.",
        about_p3: "Modern CNC kayar otomat makineleri ve güçlü üretim altyapımız sayesinde; karmaşık geometrilere sahip parçaları yüksek kalite standartlarında, seri ve güvenilir şekilde üretmekteyiz. Üretim süreçlerimizin her aşamasında kalite kontrol, ölçü hassasiyeti ve müşteri memnuniyeti ön planda tutulmaktadır.",
        about_p4: "Megatech Savunma olarak hedefimiz; teknolojiyi, mühendisliği ve hassas üretimi bir araya getirerek sektörün ihtiyaç duyduğu güvenilir çözümleri sunmak ve üretimde sürdürülebilir kalite anlayışını devam ettirmektir.",
        exp_text: "Yıllık Tecrübe",
        innovation_title: "İNOVASYON",
        inn_card1_title: "YAPAY ZEKA DESTEKLİ HASSASİYET",
        inn_card1_desc: "CNC süreçlerini optimize etmek ve sıfır hata üretim sağlamak için gelişmiş yapay zekayı entegre ediyoruz.",
        inn_card2_title: "OTONOM SİSTEMLER",
        inn_card2_desc: "Yeni nesil kara, hava ve deniz otonom savunma platformları için yüksek hassasiyetli bileşenler geliştiriyoruz.",
        inn_card3_title: "TAKTİK MATERYALLER",
        inn_card3_desc: "Kritik görev uygulamaları için gelişmiş havacılık sınıfı alaşımlar ve kompozitler üzerinde uzmanlık.",
        contact_title: "İLETİŞİM",
        contact_h3: "İLETİŞİME GEÇİN",
        contact_desc: "Uzman ekibimiz, yüksek hassasiyetli üretim ihtiyaçlarınızı görüşmek için hazır.",
        info_email: "E-posta:",
        info_location: "Konum:",
        info_phone: "Telefon:",
        placeholder_name: "Adınız",
        placeholder_email: "E-posta Adresiniz",
        placeholder_subject: "Konu",
        placeholder_message: "Mesajınız",
        btn_send: "MESAJ GÖNDER",
        footer_desc: "Gelişmiş savunma teknolojileri, havacılık mühendisliği ve taktik sistemlerde öncü. Küresel güvenliğin geleceğini inşa ediyoruz.",
        footer_capabilities: "YETENEKLER",
        footer_resources: "HIZLI BAĞLANTILAR",
        footer_contact: "İLETİŞİM",
        link_aerospace: "Havacılık Sistemleri",
        link_naval: "Deniz Mühendisliği",
        link_land: "Kara Savunması",
        link_cyber: "Siber Güvenlik",
        link_docs: "Teknik Belgeler",
        link_career: "Kariyer Portalı",
        link_press: "Basın Odası",
        link_sustainability: "Sürdürülebilirlik",
        footer_location: "Saray Mahallesi, 30. Cd. 15B 06980 Kahramankazan Ankara, Türkiye",
        footer_rights: "Tüm hakları saklıdır.",
        link_privacy: "Gizlilik Politikası",
        link_terms: "Kullanım Şartları ve KVKK Metni",
        contact_page_title: 'UZMANLARIMIZLA <span class="logo-accent">İLETİŞİME GEÇİN</span>',
        contact_page_subtitle: "Projenizin gerektirdiği hassas mühendislik çözümlerini sunmaya hazırız.",
        contact_desc_dedicated: "Teknik sorularınız veya fiyat teklifi talepleriniz için doğrudan mühendislik ekibimize ulaşın.",
        info_office: "Genel Merkez:",
        office_location: "Saray Mahallesi, 30. Cd. 15B<br>06980 Kahramankazan Ankara<br>Türkiye",
        label_name: "Ad Soyad",
        label_email: "E-posta Adresi",
        label_sector: "Sektör",
        label_message: "Mesajınız",
        placeholder_name_val: "Ahmet Yılmaz",
        placeholder_email_val: "ahmet@ornek.com",
        placeholder_message_val: "Proje gereksinimlerinizi açıklayın...",
        btn_send_secure: "EKİBİMİZLE İLETİŞİME GEÇİN",
        nav_blog: "BLOG",
        blog_title: "Savunma Sanayii ve Teknoloji Bloğu",
        blog_subtitle: "Hassas üretim ve savunma teknolojilerinin geleceğine dair güncel yazılar.",
        read_more: "Devamını Oku",
        blog_post1_title: "CNC Kayar Otomat Teknolojilerinin Savunma Sanayiindeki Rolü",
        blog_post1_excerpt: "Modern savunma platformlarında ihtiyaç duyulan mikro-hassasiyetteki parçaların üretiminde CNC kayar otomatların kritik önemi.",
        blog_post1_p1: "Savunma sanayiinde kullanılan her bir parça, hayati önem taşır. Bir füzenin güdüm sistemi, bir İHA'nın motor bloğu veya bir zırhlı aracın şanzıman dişlisi… Bu parçaların tamamı, mikro-metre seviyesinde hassasiyetle üretilmek zorundadır. İşte bu noktada CNC kayar otomat teknolojileri devreye girer. Kayar otomatlar, özellikle küçük çaplı ve karmaşık parçaların üretiminde geleneksel torna tezgahlarının çok ötesinde bir performans sunar. Megatech olarak, Türkiye'nin milli savunma projeleri için en zorlu parçaları bu ileri teknolojiyle hayata geçiriyoruz.",
        blog_post1_h2_1: "Neden Savunmada CNC Kayar Otomat?",
        blog_post1_p2: "Geleneksel torna tezgahlarından farklı olarak kayar otomatlar, malzemenin bir kılavuz burç (guide bushing) aracılığıyla desteklendiği ve malzemenin eksenel hareketiyle birlikte takımın sabit kaldığı bir prensiple çalışır. Bu yöntem, savunma platformları için kritik avantajlar sağlar:",
        blog_post1_li1: "Eşsiz Yuvarlaklık Hassasiyeti: Yüksek devirli türbin parçalarında hayati önem taşıyan 0.002 mm'ye kadar tolerans değerlerine ulaşma kabiliyeti.",
        blog_post1_li2: "Yüksek Yüzey Kalitesi: Hidrolik sistemlerde sürtünmeyi ve aşınmayı minimize eden Ra 0.2 μm yüzey pürüzlülüğü.",
        blog_post1_li3: "Yüksek Hız ve Verimlilik: 12.000 RPM'e ulaşan işleme hızları ile titanyum ve paslanmaz çelik gibi sert malzemelerin verimli işlenmesi.",
        blog_post1_h2_2: "İleri Uygulamalar ve Malzeme Karmaşıklığı",
        blog_post1_p3: "Modern savunma sistemleri, sadece küçük değil, aynı zamanda geometrik olarak son derece karmaşık parçalar gerektirir. CNC kayar otomat makinelerimiz, 10 eksene kadar hareket kabiliyeti sunarak frezeleme, delme ve diş açma işlemlerini tek bir bağlamada yapmamıza olanak tanır. Bu 'tek seferde bitirme' felsefesi, bağlama hatalarını ortadan kaldırır ve tüm özellikler arasında mükemmel eş merkezlilik sağlar.",
        blog_post1_p4: "Inconel, Monel ve havacılık sınıfı Titanyum gibi egzotik malzemeleri yüksek hassasiyetle işliyoruz. Bu malzemeler, sertlikleri ve ısı dirençleri nedeniyle işlenmesi oldukça zor karakterdedir. Ancak, özel soğutma sistemlerimiz ve yüksek basınçlı yağ beslememiz sayesinde takım aşınmasını minimize ediyor ve parça bütünlüğünü koruyoruz.",
        blog_post1_h2_3: "Megatech Mükemmeliyet Standartları",
        blog_post1_p5: "Megatech'te üretilen her parça, çok aşamalı bir denetim sürecinden geçer. CNC hücrelerimize doğrudan entegre edilmiş otomatik optik kontrol (AOI) sistemlerini kullanarak parça kalitesini gerçek zamanlı olarak izliyoruz. Bu proaktif yaklaşım, sıfır hata politikamızın sadece bir slogan değil, teknik bir gerçeklik olmasını sağlar.",
        blog_post1_p6: "En yeni Japon ve Alman CNC teknolojilerine yaptığımız yatırımlarla, daha önce ithal edilen bileşenler için Türk savunma sanayiine güvenilir ve yerli bir kaynak sağlıyoruz. Bu, milli güvenliğimizi güçlendirirken, savunma platformlarımızın mevcut olan en yüksek kaliteli parçalarla inşa edilmesini garanti altına alıyor.",
        blog_post2_title: "Türk Savunma Sanayiinde Yerlileşme ve Megatech",
        blog_post2_excerpt: "Milli projelerde dışa bağımlılığı azaltan yerli üretim çözümlerimiz ve mühendislik vizyonumuz.",
        blog_post2_p1: "Milli savunmanın teknolojik egemenlikle eş anlamlı olduğu bir çağda, kritik bileşenlerin yerlileştirilmesi artık bir seçenek değil, bir zorunluluktur. Türkiye, son on yılda KAAN, TCG Anadolu ve çeşitli İHA platformları gibi projelerle inanılmaz adımlar attı. Ancak, bu projelerin asıl başarısı, Megatech gibi yerli mühendislik firmaları tarafından üretilen alt sistemlerde ve bileşenlerde gizlidir.",
        blog_post2_p2: "Megatech olarak vizyonumuz basit: Türkiye'nin savunma platformlarında kullanılan her mekanik bileşenin sınırlarımız içerisinde tasarlanmasını, mühendisliğinin yapılmasını ve üretilmesini sağlamak. Bu misyon, AR-GE yatırımlarımızı ve teknik mükemmeliyete olan bağlılığımızı şekillendiriyor.",
        blog_post2_h2_1: "Yerlileşme Yol Haritamız",
        blog_post2_li1: "Malzeme Egemenliği: Özel havacılık çeliklerine yerli alternatifler geliştirmek için yerli malzeme bilimcilerle iş birliği yaparak tedarik zincirimizi uluslararası yaptırımlara karşı dirençli hale getiriyoruz.",
        blog_post2_li2: "Hassas İşleme: 5 eksenli işleme merkezleri ve kayar otomat teknolojisini kullanarak, daha önce sadece yabancı üreticilerden temin edilebilen karmaşık parçaları yeniden üretiyor, hatta tasarımlarını ve dayanıklılıklarını iyileştiriyoruz.",
        blog_post2_li3: "İleri Isıl İşlem: Metallerin moleküler yapısını optimize etmek için NADCAP sertifikalı ısıl işlem süreçleri uyguluyor, savunma uygulamalarının aşırı stres gereksinimlerini karşılamalarını sağlıyoruz.",
        blog_post2_h2_2: "Milli Projeler Üzerindeki Stratejik Etki",
        blog_post2_p3: "ASELSAN'ın radar sistemleri ve ROKETSAN'ın füze güdüm birimleri gibi projelere katkımız, dışa bağımlılığı doğrudan azalttı. Bu parçaları yerli olarak üreterek sadece milyonlarca dolarlık döviz tasarrufu sağlamakla kalmıyor, aynı zamanda yabancı onay beklemeksizin tasarımları değiştirme ve iyileştirme esnekliği kazanıyoruz.",
        blog_post2_p4: "Yerlileşme aynı zamanda daha hızlı geri dönüş süreleri demektir. Savunmanın hızlı dünyasında, bir tasarımı yineleme ve aylar yerine günler içinde bir prototip üretme yeteneği önemli bir taktik avantajdır. Megatech'in çevik imalat süreçleri bu hızlı geliştirme döngüsünü desteklemek üzere tasarlanmıştır.",
        blog_post2_h2_3: "Türk Mühendisliğinin Geleceğini İnşa Etmek",
        blog_post2_p5: "Biz sadece bir üretici değiliz; biz aynı zamanda gelecek nesil Türk mühendisleri için bir eğitim alanıyız. Yüksek teknolojili projelerde çalışarak ekibimiz, ülkenin endüstriyel geleceği için hayati önem taşıyan CAD/CAM, malzeme bilimi ve hassas metroloji konularında beceriler geliştirmektedir.",
        blog_post3_title: "Yapay Zeka Destekli Hassas Üretim",
        blog_post3_excerpt: "Üretim hatlarımızda yapay zeka entegrasyonu ile hata payını sıfıra indiren yeni nesil kontrol sistemleri.",
        blog_post3_p1: "Savunma sanayiinde hataya yer yoktur. Bir vida dişindeki 0,01 mm'lik sapma, bir güdüm sisteminin arızalanmasına ve görevin felaketle sonuçlanmasına neden olabilir. Bu riski ortadan kaldırmak için Megatech, üretim hatlarına gelişmiş Yapay Zekayı (AI) entegre ederek geleneksel otomasyonun ötesine geçip akıllı üretim alanına adım atmıştır.",
        blog_post3_p2: "Megatech'teki yapay zeka sadece robotlarla ilgili değildir; veriyle ilgilidir. Fabrikamızdaki her makine, merkezi yapay zeka motorumuza sürekli veri aktaran ve performansı gerçek zamanlı olarak analiz eden bağlantılı bir ekosistemin parçasıdır.",
        blog_post3_h2_1: "Yapay Zeka Hassasiyeti Nasıl Artırıyor?",
        blog_post3_p3: "CNC makinelerimize entegre edilmiş akustik emisyon sensörleri ve yüksek çözünürlüklü kameralar kullanıyoruz. Bu sensörler milisaniye düzeyinde veri yakalayarak yapay zeka algoritmalarımızın şunları yapmasını sağlar:",
        blog_post3_li1: "Takım Aşınması Tahmini: Yapay zeka, kesme işleminin ses ve titreşim modellerini analiz ederek bir takımın ne zaman arızalanacağını parça hasar görmeden önce tahmin eder ve proaktif değişime olanak tanır.",
        blog_post3_li2: "Gerçek Zamanlı Yüzey Analizi: Yüksek hızlı kameralar, parçaların işlenme sırasındaki yüzey finişini izleyerek insan gözünün kaçırabileceği mikro çatlakları veya düzensizlikleri tespit eder.",
        blog_post3_li3: "Adaptif Süreç Kontrolü: Yapay zeka malzeme sertliğinde veya sıcaklıkta hafif bir sapma tespit ederse, mükemmel hassasiyeti korumak için makinenin ilerleme hızını ve devrini otomatik olarak ayarlar.",
        blog_post3_h2_2: "Sıfır Hata Üretimine Giden Yol",
        blog_post3_p4: "Geleneksel kalite kontrol parça üretildikten sonra yapılır. Yapay zeka ile kalite kontrol, parça üretilirken yapılır. Reaktif izlemeden proaktif izlemeye bu geçiş, sıfır hata politikamızın temel taşıdır. Tesisimizden ayrılan parçaların %100'ünün ortaklarımızın tam spesifikasyonlarını karşılamasını sağlar.",
        blog_post3_p5: "Ayrıca, yapay zeka sistemlerimiz malzeme kullanımını optimize etmemize yardımcı olur. Her parça için tam olarak ne kadar malzeme gerektiğini tahmin ederek ve fireyi azaltarak, sadece ortaklarımızın maliyetlerini düşürmekle kalmıyor, aynı zamanda çevresel ayak izimizi de minimize ediyoruz.",
        blog_post3_h2_3: "Gelecek: Kendi Kendini Optimize Eden Fabrikalar",
        blog_post3_p6: "Nihai hedefimiz, tamamen kendi kendini optimize eden bir fabrika oluşturmaktır. Bu vizyonda makineler sadece kendilerini izlemekle kalmayacak, aynı zamanda ürettikleri her parçadan öğrenecek, verimliliği ve hassasiyeti sürekli artıracaktır. Megatech, Türkiye'deki bu Endüstri 4.0 devriminin ön saflarında yer almaktan gurur duymaktadır.",
        blog_post4_title: "Havacılık ve Uzayda Yüksek Hassasiyet",
        blog_post4_excerpt: "Havacılık standartlarında parça üretiminde kalite kontrol ve tolerans yönetimi.",
        blog_post5_title: "Otonom Sistemler için Kritik Bileşenler",
        blog_post5_excerpt: "İHA ve kara otonom araçlarında kullanılan yüksek dayanımlı mekanik bileşenlerin üretimi.",
        blog_post6_title: "Savunmada Sürdürülebilir Kalite",
        blog_post6_excerpt: "Savunma sanayiinde uzun ömürlü ve güvenilir sistemler için malzeme seçimi ve ısıl işlem süreçleri.",
        blog_post7_title: "Milli Muharip Uçak ve Hassas Mühendislik",
        blog_post7_excerpt: "KAAN projesinde kullanılan ileri teknoloji parça imalat süreçlerine genel bakış.",
        blog_post8_title: "İHA ve SİHA Alt Sistem Üretimi",
        blog_post8_excerpt: "Türkiye'nin gururu İHA'lar için ürettiğimiz kritik mekanik aksamlar ve teknolojik detaylar.",
        blog_post9_title: "Zırhlı Araçlarda Mekanik Hassasiyet",
        blog_post9_excerpt: "Ağır zırhlı araç platformlarında dayanıklılık ve hassasiyet dengesi.",
        blog_post10_title: "Deniz Sistemlerinde Malzeme Mühendisliği",
        blog_post4_p1: "Havacılık sektörü, tolerans kavramını sadece bir mühendislik değeri değil, bir güvenlik standardı olarak görür. Bir uçak motoru fan kanadındaki 0,05 mm'lik bir kalınlık farkı, 30.000 feet irtifada metal yorgunluğuna ve motorun parçalanmasına yol açabilir. Megatech olarak, havacılık ve uzay sistemlerinde bu toleransların nanometre seviyelerine indiği bir dünyada, hatasız üretimin sınırlarını zorluyoruz.",
        blog_post4_p2: "Havacılık imalatında başarının anahtarı, AS9100D kalite yönetim sistemine tam uyumdur. Tesisimizdeki her operasyon, bu katı havacılık standartlarına göre sertifikalandırılmıştır. Malzemenin girişinden, son parçanın sevkiyatına kadar her adım dijital olarak izlenmekte ve belgelenmektedir.",
        blog_post4_h2_1: "Havacılıkta Hassas İmalat ve Teknik Zorluklar",
        blog_post4_p3: "Havacılık parçaları genellikle Inconel, Waspaloy ve havacılık sınıfı Titanyum (Ti-6Al-4V) gibi işlenmesi son derece zor süper alaşımlardan yapılır. Bu malzemeler yüksek sıcaklıklara dayanıklıdır ancak aynı zamanda kesici takımları hızla aşındırır. Megatech, bu malzemelerin işlenmesinde uzmanlaşmış yüksek basınçlı soğutma sistemleri ve özel kaplamalı karbür takımlar kullanarak yüzey kalitesini maksimize eder.",
        blog_post4_li1: "Türbin Gövdeleri: 1000°C'nin üzerinde çalışan, termal genleşmesi kontrol altında tutulmuş hassas türbin bileşenleri.",
        blog_post4_li2: "Hidrolik Aktüatör Milleri: Uçak iniş takımları ve kontrol yüzeyleri için sıfır sızdırmazlık ve mükemmel yüzey finişi gerektiren miller.",
        blog_post4_li3: "Kritik Bağlantı Elemanları: Yüksek çekme dayanımlı, yorulmaya dirençli özel dişli saplamalar ve civatalar.",
        blog_post4_h2_2: "Metroloji ve Doğrulama Teknolojileri",
        blog_post4_p4: "Üretim bittikten sonra süreç sona ermez. Metroloji laboratuvarımızda, parçalarımız CMM (Koordinat Ölçüm Cihazı) ve lazer tarama sistemleriyle üç boyutlu olarak doğrulanır. 0.001 mm hassasiyetle yapılan bu ölçümler, her bir parçanın 'uçuşa hazır' olduğunu kanıtlar.",
        blog_post4_p5: "Ayrıca, parçalarımız üzerinde ultrasonik ve manyetik parçacık denetimi gibi tahribatsız muayene (NDT) yöntemleri uygulayarak, malzemenin iç yapısında herhangi bir mikro çatlak olmadığından emin oluyoruz. Havacılıkta 'görünmeyen' hatalar en büyük risklerdir; Megatech bu riskleri tamamen ortadan kaldırır.",
        blog_post4_h2_3: "Milli Gök Vatanın Gücü",
        blog_post4_p6: "KAAN, HÜRJET ve GÖKBEY gibi milli projelerin tedarik zincirinde yer almaktan gurur duyuyoruz. Bu platformların gökyüzündeki güvenliği, Megatech'in ürettiği her bir cıvatanın ve milin kalitesine emanettir. Yerli havacılık sanayiinin gelişmesi için teknolojik sınırları zorlamaya devam edeceğiz.",
        blog_post5_p1: "İHA, SİHA ve kara otonom araçları, savaşın doğasını değiştiriyor. Ancak bu sistemlerin kalbi, piller veya yazılımlar değil; hareket kabiliyetini sağlayan mekanik aktarma organlarıdır. Megatech, otonom platformların en zorlu koşullarda bile kusursuz çalışmasını sağlayan mekanik mühendislik çözümleri sunar.",
        blog_post5_p2: "Otonom sistemlerde dayanıklılık, sadece malzemenin sertliği değil, aynı zamanda tasarımın verimliliğidir. Ağırlığı azaltırken mukavemeti korumak, bir İHA'nın havada kalış süresini doğrudan etkiler.",
        blog_post5_h2_1: "Otonom Platformlar için Kritik Bileşenler",
        blog_post5_li1: "Rulmanlı Yataklama Sistemleri: Yüksek hızlı dron motorları için 100.000 rpm devire dayanıklı seramik bilyalı rulman yatakları.",
        blog_post5_li2: "Aktüatör Milleri: Elektro-mekanik aktüatörlerde 10.000 saat ömür testini geçen, aşınmaya dayanıklı karbür kaplamalı miller.",
        blog_post5_li3: "Redüktör Dişlileri: Yer otonom araçlarında yüksek tork gerektiren, gürültüsü azaltılmış planet dişli sistemleri.",
        blog_post5_h2_2: "Yazılım ve Donanım Uyumu",
        blog_post5_p3: "Bir otonom aracın yapay zekası ne kadar gelişmiş olursa olsun, bu zekayı harekete dönüştüren mekanik aksam yetersizse araç görevini yapamaz. Megatech olarak, sensörlerden gelen verinin milisaniyeler içinde fiziksel harekete dönüşmesini sağlayan sıfır boşluklu (zero-backlash) mekanizmalar üretiyoruz.",
        blog_post5_p4: "Türkiye'nin önde gelen İHA üreticilerine doğrudan tedarik sağlayan Megatech, bu bileşenlerin yurt dışı bağımlılığını ortadan kaldırarak milli otonom sistemlerin kesintisiz görev yapmasını garanti altına almaktadır.",
        blog_post6_p1: "Bir savaş uçağının ömrü 30-40 yıldır. Bu süre boyunca motoru defalarca revizyondan geçer, ancak gövde ve kritik yapısal parçalar değişmez. İşte burada \"sürdürülebilir kalite\" kavramı devreye girer: Bir parçanın sadece üretildiği gün değil, 30 yıl sonra da aynı performansı vermesi.",
        blog_post6_p2: "Kalite, Megatech'te bir departman değil, bir yaşam biçimidir. Ürettiğimiz her parçanın arkasında yılların deneyimi ve en ileri malzeme bilimi teknikleri yatmaktadır.",
        blog_post6_h2_1: "Megatech Kalite Felsefesi ve Süreçleri",
        blog_post6_li1: "Malzeme Seçimi: 4340, 300M, 17-4 PH gibi yüksek dayanımlı çeliklerin yanı sıra havacılık sınıfı titanyum (Ti-6Al-4V) kullanımı ve spektral analiz doğrulaması.",
        blog_post6_li2: "Isıl İşlem Süreçleri: Vakum fırınlarında atmosfer kontrollü olarak uygulanan temperleme, söndürme ve -196°C'ye varan kriyojenik işlemler ile moleküler stabilizasyon.",
        blog_post6_li3: "Yüzey İşlemleri: Nikel kaplama, kadmiyum kaplama veya havacılıkta tercih edilen pasivasyon ile korozyon direncinin maksimize edilmesi ve tuz sisi testleri.",
        blog_post6_h2_2: "Zorlu Çevre Testleri",
        blog_post6_p3: "Megatech'ten çıkan her kritik parça, simülasyon ortamında ve fiziksel testlerde zorlu çevre koşullarına tabi tutulur. Sıcaklık döngüsü, yüksek frekanslı titreşim ve şok testleri, parçanın operasyonel ömrü boyunca güvenilir kalacağını kanıtlar.",
        blog_post6_p4: "Kalite, bir başlangıç değil, bir bitiş noktasıdır. Megatech olarak, 'sürdürülebilir kalite' yaklaşımımızla Türk savunma sanayiinin en güvenilir çözüm ortağı olmaya devam ediyoruz.",
        blog_post7_p1: "KAAN, Türkiye'nin savunma sanayiinde geldiği noktanın somut bir göstergesidir. Bu proje, sadece bir uçak inşa etmekten ibaret değildir; aynı zamanda bir ülkenin hassas mühendislik kabiliyetinin testidir. 5. nesil bir savaş uçağı, radar görünmezliği (stealth) ve yüksek manevra kabiliyeti için binlerce mikro ve makro parçanın mükemmel uyumunu gerektirir.",
        blog_post7_p2: "Megatech olarak KAAN projesindeki rolümüz, uçağın en kritik mekanik alt sistemlerinin imalatını kapsamaktadır. Bu parçalar, uçağın gövde bütünlüğünü ve operasyonel güvenliğini sağlar.",
        blog_post7_h2_1: "Milli Muharip Uçak ve Hassas Mühendislik Uygulamaları",
        blog_post7_li1: "Kokpit Güvenlik Kilidi Mekanizmaları: Pilotun yüksek G kuvveti altında ve binlerce km/s hızla giderken güvende kalmasını sağlayan, düşük ağırlıkta ve aşırı yüksek dayanımlı titanyum mekanizmalar.",
        blog_post7_li2: "Silah Yuvası Aktüatörleri: Radar görünmezliği için gövde içine gizlenmiş mühimmatların saniyeler içinde açılıp kapanmasını sağlayan hassas hidrolik ve mekanik sistemler.",
        blog_post7_li3: "İniş Takımı Destek Elemanları: 20 tonun üzerindeki uçağın iniş anında maruz kaldığı devasa darbe yüklerini emen, özel ısıl işlem görmüş çelik parçalar.",
        blog_post7_h2_2: "Blok Malzemeden Talaşlı İmalat (Monolitik Yapılar)",
        blog_post7_p3: "Havacılıkta parça birleştirmek yerine, parçaları tek bir blok malzemeden işlemek (monolithic manufacturing) yapısal zayıflıkları ortadan kaldırır. Megatech, 5 eksenli CNC teknolojisi ile büyük blokları mikron hassasiyetinde işleyerek KAAN'ın hafif ve dayanıklı gövde yapısına katkıda bulunur.",
        blog_post7_p4: "Bu bileşenlerin her biri, üretimden montaja kadar dijital olarak kayıt altındadır. Her bir mikronluk sapma raporlanır ve parça üzerindeki her bir işlem adımının tam izlenebilirliği (traceability) garanti edilir.",
        blog_post8_p1: "Bayraktar TB2, AKINCI ve ANKA… Bu araçlar, Türkiye'nin gururu olduğu kadar, dünya savunma literatürünü değiştiren başarı hikayeleridir. İHA'ların bu başarısı sadece yazılımlarına değil, binlerce saat boyunca arıza yapmadan çalışan mekanik alt bileşenlerine de bağlıdır.",
        blog_post8_p2: "Megatech, bu platformların görünmeyen kahramanı olan binlerce kritik alt bileşeni üretmektedir. Bir İHA'nın motorundan kanatçıklarına kadar her noktada Megatech'in hassas dokunuşu vardır.",
        blog_post8_h2_1: "İHA ve SİHA Alt Sistem Üretimi ve Teknolojik Detaylar",
        blog_post8_li1: "Trim Aktüatör Gövdeleri: Uçağın uçuş yüzeylerini (kanatçıklar) kontrol eden servo motorların ana gövdesi. Aerodinamik direnç için kusursuz yüzey kalitesi.",
        blog_post8_li2: "Yakıt Pompası Milleri: 30.000 feet irtifada, -50°C sıcaklıkta dahi yakıt akışını kesintisiz sağlayan, aşınmaya ve soğuğa dayanıklı özel tasarım miller.",
        blog_post8_li3: "Paraşüt Sistemi Mekanizmaları: Acil durumlarda İHA'yı koruyan paraşütün fırlatılmasını sağlayan, piroteknik içermeyen ancak anlık tepki veren mekanik tetikleyiciler.",
        blog_post8_h2_2: "NATO Standartlarında Güvenilirlik",
        blog_post8_p3: "Megatech farkı: Bu parçaların tamamı, yerli sermaye ve yerli mühendislikle, yüksek adetli ve dünya standartlarında rekabetçi fiyatlarla üretilmektedir. Üretilen her parti, NATO (STANAG) standartlarında testlerden geçirilerek envantere girmektedir.",
        blog_post8_p4: "Yerlilik oranımızı her geçen gün artırırken, sadece Türkiye'nin değil, dost ve müttefik ülkelerin İHA filoları için de kritik parça tedarikçisi olma yolunda emin adımlarla ilerliyoruz.",
        blog_post9_p1: "Zırhlı araçlar dendiğinde akla ilk gelen şey kaba bir dayanıklılıktır. Ancak, bir Altay tankı veya Pars zırhlı aracı, sadece kalın zırh plakalarından ibaret değildir. Bu araçların hareket kabiliyetini ve ateş gücünü sağlayan mekanik sistemler, aslında bir saat mekanizması kadar hassastır.",
        blog_post9_p2: "Megatech, zırhlı araçların en zorlu arazi koşullarında ve çatışma anında sorunsuz çalışmasını sağlayan mekanik mühendislik çözümleri üretir. Dayanıklılık ve hassasiyetin kesiştiği noktadayız.",
        blog_post9_h2_1: "Zırhlı Araçlarda Mekanik Hassasiyet ve Operasyonel Güvenlik",
        blog_post9_li1: "Palet Pimleri ve Burçları: 60 tonluk yükü taşıyan ve km'lerce yol boyunca aşınmaya direnen, özel yüzey sertleştirme teknikleri uygulanmış pimler.",
        blog_post9_li2: "Taret Döndürme Redüktörü Dişlileri: Tank tareti saniyeler içinde 360 derece dönerken, ana silahın geri tepme darbesine dayanabilen özel dişli geometrileri.",
        blog_post9_li3: "Süspansiyon ve Şok Emici Silindirler: Engebeli arazide sürati koruyan, hidrolik ünitelerin mikron seviyesinde honlanmış iç yüzeyleri.",
        blog_post9_h2_2: "Geri Tepme ve Darbe Mühendisliği",
        blog_post9_p3: "Büyük kalibreli silahların ateşlenmesi sırasında oluşan impulsive (darbeli) kuvvetler, aracın tüm mekanik aksamını test eder. Megatech olarak, bu şok dalgalarına dayanıklı, yorulma ömrü yüksek parçalar tasarlıyor ve üretiyoruz.",
        blog_post9_p4: "Tüm bu parçalar, milimetrik sapmaların aracın savaş kabiliyetini doğrudan etkileyebileceği bilinciyle, Megatech mühendisleri tarafından en modern CNC tezgahlarında titizlikle işlenmektedir.",
        blog_post10_p1: "Tuzlu su, bir makine mühendisinin en büyük düşmanıdır. Denizaltı ve savaş gemileri, sadece sürekli korozyona maruz kalmakla kalmaz, aynı zamanda derin deniz basıncı ve değişken termal yükler altında çalışan dünyanın en zorlu mekanik platformlarıdır. Megatech, bu zorlu koşullara dayanabilecek malzeme mühendisliği çözümleri sunmaktadır.",
        blog_post10_p2: "Deniz sistemlerinde kullanılan parçalar, en ufak bir yüzey kusurunda korozyon başlangıcına (pitting) neden olabilir. Bu yüzden, imalat sonrası yüzey kalitesi ve malzeme seçimi hayati önem taşır.",
        blog_post10_h2_1: "Korozyona Karşı Megatech Çözümleri ve Denizaltı Teknolojileri",
        blog_post10_li1: "Şaft ve Pervane Göbekleri: Dubleks ve süper dubleks paslanmaz çeliklerden (Örn: 2205, 2507) üretim. Bu malzemeler, deniz suyunda oluşan klorür iyonlarına karşı üstün direnç ve yüksek mekanik dayanım gösterir.",
        blog_post10_li2: "Sızdırmazlık Elemanları ve Valfler: Monel (nikel-bakır alaşımı) veya Hastelloy'dan imal edilen, derin deniz basıncında dahi sızdırmazlık özelliğini kaybetmeyen kritik parçalar.",
        blog_post10_li3: "Kritik Bağlantı Elemanları: Havacılık sınıfı titanyum (Grade 5) veya yüzeyi nikel-kobalt kaplanmış, yüksek çekme dayanımlı ve korozyon ömrü uzatılmış özel cıvatalar.",
        blog_post10_h2_2: "MİLGEM ve MİLDEN Projelerine Katkı",
        blog_post10_p3: "Megatech, Türkiye'nin milli gemi (MİLGEM) ve milli denizaltı (MİLDEN) projelerinde stratejik bir tedarikçidir. Denizaltıların sessiz seyir yapabilmesi için gerekli olan ultra-hassas toleranslı tahrik sistemi bileşenlerini, en modern talaşlı imalat yöntemleriyle üretiyoruz.",
        blog_post10_p4: "Mavi Vatan'ın savunmasında görev alan platformlarımızın, on yıllar boyunca korozyon sorunu yaşamadan görev yapabilmesi için malzeme biliminin sınırlarını zorlamaya devam ediyoruz.",
        blog_post11_p1: "Bir füze fırlatıldığı andan itibaren, birkaç saniye içinde ses hızının katlarına (Mach hızları) ulaşır ve atmosferik sürtünme nedeniyle yüzlerce derecelik sıcaklıklara maruz kalır. Bu ekstrem ortamda, parçanın genleşme katsayısından iç yapı bütünlüğüne kadar her detay, füzenin hedefi vurup vuramayacağını belirler.",
        blog_post11_p2: "Megatech, roket ve füze sistemleri için yüksek riskli ve yüksek hassasiyetli üretimlerde uzmanlaşmış bir çözüm ortağıdır. Ürettiğimiz her bileşen, milli savunmamızın caydırıcı gücünün bir parçasıdır.",
        blog_post11_h2_1: "Roket ve Füze Sistemleri İmalatı ve Isıl Direnç Mühendisliği",
        blog_post11_li1: "Roket Motoru Gövdeleri: Yüksek iç basınç ve termal şoka dayanıklı, 15-5 PH veya 17-4 PH paslanmaz çeliklerden hassas boru ve gövde imalatı.",
        blog_post11_li2: "Nozul Tutucular ve Gaz Yönlendiriciler: Yakıtın yanmasıyla oluşan aşındırıcı ve süper-sıcak gazlara karşı dirençli, özel seramik veya tungsten alaşımlı bileşenler.",
        blog_post11_li3: "Güdüm Kanatçığı Tahrik Milleri: Füzenin havada manevra yapmasını sağlayan, milisaniyeler içinde tepki veren ve yüksek tork taşıyan hassas mekanik miller.",
        blog_post11_h2_2: "ROKETSAN ve Milli Füze Ailesi",
        blog_post11_p3: "ROKETSAN gibi dünya devi kurumlarla yürüttüğümüz projelerde, yerli füzelerimizin (HİSAR, SİPER, ATMACA) kritik parçalarını üretiyoruz. Bu parçalar üzerinde uyguladığımız röntgen (X-ray) ve ultrasonik testler, malzemenin içinde görünmeyen hiçbir kusur kalmadığını garanti eder.",
        blog_post11_p4: "Hassas talaşlı imalat kabiliyetimiz, roket sistemlerinin sadece dayanıklı değil, aynı zamanda hedefe yönelirken mükemmel bir aerodinamik kararlılık sergilemesini sağlar.",
        blog_post12_p1: "İlk bakışta tıbbi cihaz üretimi ile savunma sanayii birbirine zıt gibi görünse de, mühendislik temelinde ikisi de aynı prensibe dayanır: Hata payı olmayan hassasiyet. Bir cerrahın kullandığı kemik vidası ile bir füzenin gövde vidası, aslında benzer tolerans ve malzeme gereksinimlerine sahiptir.",
        blog_post12_p2: "Megatech, medikal sektördeki nanometre seviyesindeki hassasiyet tecrübesini, savunma sanayiinin sağlamlık gereksinimleriyle harmanlayarak benzersiz bir üretim sinerjisi yaratmıştır.",
        blog_post12_h2_1: "Tıbbi Cihaz ve Savunma Teknolojileri Arasındaki Mühendislik Köprüsü",
        blog_post12_li1: "Malzeme Benzerliği: Tıbbi implantlarda kullanılan Titanyum Grade 5, savunma sanayiinde uçak gövde parçaları için en ideal malzemedir. Her iki alanda da biyo-uyumluluk veya korozyon direnci esastır.",
        blog_post12_li2: "Kalite Sistemleri Entegrasyonu: ISO 13485 (Medikal) ve AS9100D (Savunma) standartları arasındaki benzerlik, üretim hatlarımızın her iki sektör için de en üst düzeyde denetlenebilir olmasını sağlar.",
        blog_post12_li3: "Mikro-İşleme Kabiliyeti: Cerrahi robotik kollar için ürettiğimiz mikro dişlilerdeki hassasiyetimizi, İHA'ların kamera stabilizasyon sistemlerine (gimbal) aktarıyoruz.",
        blog_post12_h2_2: "Sektörler Arası Bilgi Transferi",
        blog_post12_p3: "Medikal sektörün gerektirdiği aşırı temiz üretim ve pürüzsüz yüzey standartları, savunma sanayiindeki parçalarımızın yorulma ömrünü artırmaktadır. Savunma sanayiinde geliştirdiğimiz yüksek mukavemetli işleme teknikleri ise medikal cihazlarımızın daha dayanıklı olmasını sağlamaktadır.",
        blog_post12_p4: "Megatech olarak, disiplinler arası bu yaklaşımımızla inovasyonu sadece bir sektörle sınırlı tutmuyor, her iki alanda da Türkiye'nin teknolojik yetkinliğini artırıyoruz.",
        blog_post13_p1: "Dördüncü sanayi devrimi (Endüstri 4.0), üretim tesislerini statik yapılar olmaktan çıkarıp canlı, öğrenen ve evrimleşen ekosistemlere dönüştürmektedir. Savunma sanayii gibi hata toleransının sıfır olduğu bir sektörde, bu dijital dönüşüm sadece bir verimlilik aracı değil, aynı zamanda stratejik bir üstünlük kaynağıdır.",
        blog_post13_p2: "Megatech, üretim hattındaki her bir CNC tezgahını, ölçüm cihazını ve personel terminalini tek bir dijital sinir sistemine bağlayarak 'Akıllı Fabrika' konseptini tam anlamıyla hayata geçirmiştir.",
        blog_post13_h2_1: "Megatech Akıllı Fabrika Bileşenleri ve Dijital Dönüşüm",
        blog_post13_li1: "IoT ve Canlı İzleme: Her makineden alınan anlık veriler (ilerleme hızları, takım yükleri, enerji tüketimi), merkezi bir bulut sisteminde analiz edilir. Bu sayede üretim darboğazları oluşmadan tespit edilir.",
        blog_post13_li2: "Dijital İkiz (Digital Twin): Üretilecek her parça için önce sanal bir model oluşturulur. Kesme stratejileri bu sanal model üzerinde test edilerek, gerçek tezgahta oluşabilecek çarpışma veya hatalar %100 oranında önlenir.",
        blog_post13_li3: "MES ve Tam İzlenebilirlik: Malzeme ambarından çıkan her hammadde, bir dijital kimlik (RFID/Barkod) kazanır. Müşterimiz, siparişinin hangi tezgahta, hangi operatör tarafından ve hangi hassasiyette işlendiğini anlık olarak takip edebilir.",
        blog_post13_h2_2: "Veriye Dayalı Karar Destek Mekanizmaları",
        blog_post13_p3: "Yapay zeka destekli algoritmalarımız, geçmiş üretim verilerini analiz ederek gelecekteki projeler için en optimize işleme parametrelerini önerir. Bu, 'kurumsal hafıza' oluşturmamızı ve her yeni projeye bir adım önde başlamamızı sağlar.",
        blog_post13_p4: "Megatech olarak, Endüstri 4.0'ı sadece teknoloji satın almak olarak değil, üretim kültürümüzü dijital çağa adapte etmek olarak görüyoruz.",
        blog_post14_p1: "Türk savunma sanayii, son on yılda kabuğunu kırarak küresel bir oyuncu haline gelmiştir. Bugün sadece kendi ihtiyacını karşılayan değil, dünyaya teknoloji ihraç eden bir Türkiye vardır. Megatech, bu ihracat başarısının arkasındaki gizli güçlerden biridir: KOBİ seviyesinde yüksek teknoloji ve mükemmeliyet.",
        blog_post14_p2: "Küresel devlerle (Lockheed Martin, Airbus, Boeing gibi) rekabet edebilmek için sadece 'ucuz' olmak yetmez; 'en iyi' ve 'en güvenilir' olmanız gerekir. Megatech'in ihracat stratejisi tam da bu mükemmeliyet üzerine kuruludur.",
        blog_post14_h2_1: "Küresel Pazarda Türk Mühendisliğinin İmzası",
        blog_post14_li1: "Sertifikasyon Gücü: AS9100D Havacılık ve Uzay Kalite Yönetim Sistemi sertifikamız, parçalarımızın dünyanın her yerinde 'uçuşa hazır' kabul edilmesini sağlar. Bu, küresel tedarik zincirlerine giriş pasaportumuzdur.",
        blog_post14_li2: "CNC Kayar Otomat Uzmanlığı: Karmaşık ve küçük parçaların üretiminde dünyadaki en iyi maliyet-kalite oranını sunuyoruz. Geleneksel yöntemlerden %40 daha hızlı üretim yaparak rakiplerimizin önüne geçiyoruz.",
        blog_post14_li3: "Kültürel Adaptasyon ve Hızlı Geri Dönüş: Farklı ülkelerdeki iş ortaklarımızın teknik dillerini ve standartlarını (DIN, ANSI, MIL-SPEC) anlıyor, prototip taleplerine günler içinde cevap veriyoruz.",
        blog_post14_h2_2: "Teknoloji Elçiliği",
        blog_post14_p3: "İhraç ettiğimiz her bir parça, aslında Türk mühendisliğinin birer kartvizitidir. Megatech olarak, Avrupa'dan Orta Doğu'ya kadar geniş bir coğrafyada kritik projelerin parçası olmaktan ve Türkiye'nin teknolojik itibarını artırmaktan gurur duyuyoruz.",
        blog_post15_p1: "Megatech için gelecek, dünün başarıları üzerine inşa edilen ama bugünün sınırlarını zorlayan bir yolculuktur. 'Vizyon 2030' planımız, firmamızı sadece bir imalatçı olmaktan çıkarıp, dünya çapında bir 'İleri İmalat Teknolojileri Merkezi' haline getirmeyi hedeflemektedir.",
        blog_post15_p2: "Önümüzdeki on yıl, imalat teknolojilerinde radikal değişimlere sahne olacak. Megatech, bu değişimin takipçisi değil, yönlendiricisi olma niyetindedir.",
        blog_post15_h2_1: "Megatech Vizyon 2030: Geleceğin Yol Haritası",
        blog_post15_li1: "Tam Otonom Üretim: Hedefimiz, 2030 yılına kadar üretim hatlarımızın %90'ını insan müdahalesi olmadan, karanlık fabrika (lights-out manufacturing) konseptiyle 7/24 çalışır hale getirmektir.",
        blog_post15_li2: "Nanoteknoloji ve Yeni Nesil Materyaller: Graphen takviyeli kompozitler ve ultra hafif magnezyum alaşımlarının işlenmesinde dünya lideri olmak için AR-GE laboratuvarlarımızı kuruyoruz.",
        blog_post15_li3: "Sürdürülebilir ve Yeşil Savunma: Üretim tesisimizin enerji ihtiyacının %100'ünü yenilenebilir kaynaklardan karşılayarak, karbon ayak izi sıfır olan 'Yeşil Savunma İmalatı' öncüsü olacağız.",
        blog_post15_h2_2: "Küresel Mühendislik Ağı",
        blog_post15_p3: "Ankara merkezli üretimimizi, Avrupa ve Amerika'da açacağımız tasarım ve mühendislik ofisleriyle destekleyerek, Megatech'i bir dünya markası haline getireceğiz. Sadece parça üretmiyoruz; küresel güvenliğin geleceğini inşa ediyoruz.",
        blog_post15_p4: "Gelecek, onu bugünden tasarlayanlarındır. Megatech ile bu geleceğe hazır olun.",
        back_to_blog: "Blog'a dön",
        open_in_maps: "Haritalarda Aç"
    }
};

let currentLang = 'tr';

function toggleLanguage() {
    currentLang = currentLang === 'en' ? 'tr' : 'en';
    updateContent();
    document.getElementById('lang-toggle').innerText = currentLang === 'en' ? 'TR' : 'EN';
    document.documentElement.setAttribute('lang', currentLang);
    localStorage.setItem('preferredLang', currentLang);
}

function updateContent() {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key];
        }
    });

    const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
    placeholders.forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[currentLang][key]) {
            el.setAttribute('placeholder', translations[currentLang][key]);
        }
    });
}

document.getElementById('lang-toggle').addEventListener('click', toggleLanguage);

// Mobile Menu Toggle
const mobileMenu = document.getElementById('mobile-menu');
const navLinks = document.querySelector('.nav-links');

if (mobileMenu) {
    mobileMenu.addEventListener('click', () => {
        mobileMenu.classList.toggle('active');
        navLinks.classList.toggle('active');
    });
}

// Close menu when a link is clicked
document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', () => {
        if (mobileMenu) {
            mobileMenu.classList.remove('active');
            navLinks.classList.remove('active');
        }
    });
});

// Initialize with Turkish by default
window.onload = () => {
    currentLang = 'tr';
    updateContent();
    document.getElementById('lang-toggle').innerText = 'EN';
    document.documentElement.setAttribute('lang', 'tr');
    localStorage.setItem('preferredLang', 'tr');
};
